// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Map/MapCell.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class POGOFortData;
@class POGOFortSummary;
@class POGOMapPokemon;
@class POGONearbyPokemon;
@class POGOSpawnPoint;
@class POGOWildPokemon;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - POGOMapCellRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface POGOMapCellRoot : GPBRootObject
@end

#pragma mark - POGOMapCell

typedef GPB_ENUM(POGOMapCell_FieldNumber) {
  POGOMapCell_FieldNumber_S2CellId = 1,
  POGOMapCell_FieldNumber_CurrentTimestampMs = 2,
  POGOMapCell_FieldNumber_FortsArray = 3,
  POGOMapCell_FieldNumber_SpawnPointsArray = 4,
  POGOMapCell_FieldNumber_WildPokemonsArray = 5,
  POGOMapCell_FieldNumber_DeletedObjectsArray = 6,
  POGOMapCell_FieldNumber_IsTruncatedList = 7,
  POGOMapCell_FieldNumber_FortSummariesArray = 8,
  POGOMapCell_FieldNumber_DecimatedSpawnPointsArray = 9,
  POGOMapCell_FieldNumber_CatchablePokemonsArray = 10,
  POGOMapCell_FieldNumber_NearbyPokemonsArray = 11,
};

/// A cell is a geographical "zone" containing objects like pokemon, gyms, and pokestops.
@interface POGOMapCell : GPBMessage

/// S2 geographic area that the cell covers (http://s2map.com/) (https://code.google.com/archive/p/s2-geometry-library/)
@property(nonatomic, readwrite) uint64_t s2CellId;

@property(nonatomic, readwrite) int64_t currentTimestampMs;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<POGOFortData*> *fortsArray;
/// The number of items in @c fortsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger fortsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<POGOSpawnPoint*> *spawnPointsArray;
/// The number of items in @c spawnPointsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger spawnPointsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *deletedObjectsArray;
/// The number of items in @c deletedObjectsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger deletedObjectsArray_Count;

@property(nonatomic, readwrite) BOOL isTruncatedList;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<POGOFortSummary*> *fortSummariesArray;
/// The number of items in @c fortSummariesArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger fortSummariesArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<POGOSpawnPoint*> *decimatedSpawnPointsArray;
/// The number of items in @c decimatedSpawnPointsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger decimatedSpawnPointsArray_Count;

/// Pokemon within 2 steps or less.
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<POGOWildPokemon*> *wildPokemonsArray;
/// The number of items in @c wildPokemonsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger wildPokemonsArray_Count;

/// Pokemon within 1 step or none.
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<POGOMapPokemon*> *catchablePokemonsArray;
/// The number of items in @c catchablePokemonsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger catchablePokemonsArray_Count;

/// Pokemon farther away than 2 steps, but still in the area.
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<POGONearbyPokemon*> *nearbyPokemonsArray;
/// The number of items in @c nearbyPokemonsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger nearbyPokemonsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
