// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Settings/GlobalSettings.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Settings/GlobalSettings.pbobjc.h"
 #import "POGOProtos/Settings/FortSettings.pbobjc.h"
 #import "POGOProtos/Settings/MapSettings.pbobjc.h"
 #import "POGOProtos/Settings/LevelSettings.pbobjc.h"
 #import "POGOProtos/Settings/InventorySettings.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - POGOGlobalSettingsRoot

@implementation POGOGlobalSettingsRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[POGOFortSettingsRoot extensionRegistry]];
    [registry addExtensions:[POGOMapSettingsRoot extensionRegistry]];
    [registry addExtensions:[POGOLevelSettingsRoot extensionRegistry]];
    [registry addExtensions:[POGOInventorySettingsRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - POGOGlobalSettingsRoot_FileDescriptor

static GPBFileDescriptor *POGOGlobalSettingsRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Settings"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - POGOGlobalSettings

@implementation POGOGlobalSettings

@dynamic hasFortSettings, fortSettings;
@dynamic hasMapSettings, mapSettings;
@dynamic hasLevelSettings, levelSettings;
@dynamic hasInventorySettings, inventorySettings;
@dynamic minimumClientVersion;

typedef struct POGOGlobalSettings__storage_ {
  uint32_t _has_storage_[1];
  POGOFortSettings *fortSettings;
  POGOMapSettings *mapSettings;
  POGOLevelSettings *levelSettings;
  POGOInventorySettings *inventorySettings;
  NSString *minimumClientVersion;
} POGOGlobalSettings__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "fortSettings",
        .dataTypeSpecific.className = GPBStringifySymbol(POGOFortSettings),
        .number = POGOGlobalSettings_FieldNumber_FortSettings,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(POGOGlobalSettings__storage_, fortSettings),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "mapSettings",
        .dataTypeSpecific.className = GPBStringifySymbol(POGOMapSettings),
        .number = POGOGlobalSettings_FieldNumber_MapSettings,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(POGOGlobalSettings__storage_, mapSettings),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "levelSettings",
        .dataTypeSpecific.className = GPBStringifySymbol(POGOLevelSettings),
        .number = POGOGlobalSettings_FieldNumber_LevelSettings,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(POGOGlobalSettings__storage_, levelSettings),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "inventorySettings",
        .dataTypeSpecific.className = GPBStringifySymbol(POGOInventorySettings),
        .number = POGOGlobalSettings_FieldNumber_InventorySettings,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(POGOGlobalSettings__storage_, inventorySettings),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "minimumClientVersion",
        .dataTypeSpecific.className = NULL,
        .number = POGOGlobalSettings_FieldNumber_MinimumClientVersion,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(POGOGlobalSettings__storage_, minimumClientVersion),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[POGOGlobalSettings class]
                                     rootClass:[POGOGlobalSettingsRoot class]
                                          file:POGOGlobalSettingsRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(POGOGlobalSettings__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
