// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Envelopes/Unknown6.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Networking/Envelopes/Unknown6.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - POGOUnknown6Root

@implementation POGOUnknown6Root

@end

#pragma mark - POGOUnknown6Root_FileDescriptor

static GPBFileDescriptor *POGOUnknown6Root_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Networking.Envelopes"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - POGOUnknown6

@implementation POGOUnknown6

@dynamic unknown1;
@dynamic hasUnknown2, unknown2;

typedef struct POGOUnknown6__storage_ {
  uint32_t _has_storage_[1];
  int32_t unknown1;
  POGOUnknown6_Unknown2 *unknown2;
} POGOUnknown6__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "unknown1",
        .dataTypeSpecific.className = NULL,
        .number = POGOUnknown6_FieldNumber_Unknown1,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(POGOUnknown6__storage_, unknown1),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "unknown2",
        .dataTypeSpecific.className = GPBStringifySymbol(POGOUnknown6_Unknown2),
        .number = POGOUnknown6_FieldNumber_Unknown2,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(POGOUnknown6__storage_, unknown2),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[POGOUnknown6 class]
                                     rootClass:[POGOUnknown6Root class]
                                          file:POGOUnknown6Root_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(POGOUnknown6__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - POGOUnknown6_Unknown2

@implementation POGOUnknown6_Unknown2

@dynamic unknown1;

typedef struct POGOUnknown6_Unknown2__storage_ {
  uint32_t _has_storage_[1];
  NSData *unknown1;
} POGOUnknown6_Unknown2__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "unknown1",
        .dataTypeSpecific.className = NULL,
        .number = POGOUnknown6_Unknown2_FieldNumber_Unknown1,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(POGOUnknown6_Unknown2__storage_, unknown1),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[POGOUnknown6_Unknown2 class]
                                     rootClass:[POGOUnknown6Root class]
                                          file:POGOUnknown6Root_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(POGOUnknown6_Unknown2__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
