// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Requests/Messages/EncounterMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Networking/Requests/Messages/EncounterMessage.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - POGOEncounterMessageRoot

@implementation POGOEncounterMessageRoot

@end

#pragma mark - POGOEncounterMessageRoot_FileDescriptor

static GPBFileDescriptor *POGOEncounterMessageRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Networking.Requests.Messages"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - POGOEncounterMessage

@implementation POGOEncounterMessage

@dynamic encounterId;
@dynamic spawnPointId;
@dynamic playerLatitude;
@dynamic playerLongitude;

typedef struct POGOEncounterMessage__storage_ {
  uint32_t _has_storage_[1];
  NSString *spawnPointId;
  uint64_t encounterId;
  double playerLatitude;
  double playerLongitude;
} POGOEncounterMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "encounterId",
        .dataTypeSpecific.className = NULL,
        .number = POGOEncounterMessage_FieldNumber_EncounterId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(POGOEncounterMessage__storage_, encounterId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFixed64,
      },
      {
        .name = "spawnPointId",
        .dataTypeSpecific.className = NULL,
        .number = POGOEncounterMessage_FieldNumber_SpawnPointId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(POGOEncounterMessage__storage_, spawnPointId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "playerLatitude",
        .dataTypeSpecific.className = NULL,
        .number = POGOEncounterMessage_FieldNumber_PlayerLatitude,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(POGOEncounterMessage__storage_, playerLatitude),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "playerLongitude",
        .dataTypeSpecific.className = NULL,
        .number = POGOEncounterMessage_FieldNumber_PlayerLongitude,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(POGOEncounterMessage__storage_, playerLongitude),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[POGOEncounterMessage class]
                                     rootClass:[POGOEncounterMessageRoot class]
                                          file:POGOEncounterMessageRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(POGOEncounterMessage__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
