// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Requests/Messages/EquipBadgeMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Networking/Requests/Messages/EquipBadgeMessage.pbobjc.h"
 #import "POGOProtos/Enums/BadgeType.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - POGOEquipBadgeMessageRoot

@implementation POGOEquipBadgeMessageRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[POGOBadgeTypeRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - POGOEquipBadgeMessageRoot_FileDescriptor

static GPBFileDescriptor *POGOEquipBadgeMessageRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Networking.Requests.Messages"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - POGOEquipBadgeMessage

@implementation POGOEquipBadgeMessage

@dynamic badgeType;

typedef struct POGOEquipBadgeMessage__storage_ {
  uint32_t _has_storage_[1];
  POGOBadgeType badgeType;
} POGOEquipBadgeMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "badgeType",
        .dataTypeSpecific.enumDescFunc = POGOBadgeType_EnumDescriptor,
        .number = POGOEquipBadgeMessage_FieldNumber_BadgeType,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(POGOEquipBadgeMessage__storage_, badgeType),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[POGOEquipBadgeMessage class]
                                     rootClass:[POGOEquipBadgeMessageRoot class]
                                          file:POGOEquipBadgeMessageRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(POGOEquipBadgeMessage__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t POGOEquipBadgeMessage_BadgeType_RawValue(POGOEquipBadgeMessage *message) {
  GPBDescriptor *descriptor = [POGOEquipBadgeMessage descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGOEquipBadgeMessage_FieldNumber_BadgeType];
  return GPBGetMessageInt32Field(message, field);
}

void SetPOGOEquipBadgeMessage_BadgeType_RawValue(POGOEquipBadgeMessage *message, int32_t value) {
  GPBDescriptor *descriptor = [POGOEquipBadgeMessage descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGOEquipBadgeMessage_FieldNumber_BadgeType];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
