// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Requests/Messages/GetMapObjectsMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Networking/Requests/Messages/GetMapObjectsMessage.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - POGOGetMapObjectsMessageRoot

@implementation POGOGetMapObjectsMessageRoot

@end

#pragma mark - POGOGetMapObjectsMessageRoot_FileDescriptor

static GPBFileDescriptor *POGOGetMapObjectsMessageRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Networking.Requests.Messages"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - POGOGetMapObjectsMessage

@implementation POGOGetMapObjectsMessage

@dynamic cellIdArray, cellIdArray_Count;
@dynamic sinceTimestampMsArray, sinceTimestampMsArray_Count;
@dynamic latitude;
@dynamic longitude;

typedef struct POGOGetMapObjectsMessage__storage_ {
  uint32_t _has_storage_[1];
  GPBUInt64Array *cellIdArray;
  GPBInt64Array *sinceTimestampMsArray;
  double latitude;
  double longitude;
} POGOGetMapObjectsMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "cellIdArray",
        .dataTypeSpecific.className = NULL,
        .number = POGOGetMapObjectsMessage_FieldNumber_CellIdArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(POGOGetMapObjectsMessage__storage_, cellIdArray),
        .flags = GPBFieldRepeated | GPBFieldPacked,
        .dataType = GPBDataTypeUInt64,
      },
      {
        .name = "sinceTimestampMsArray",
        .dataTypeSpecific.className = NULL,
        .number = POGOGetMapObjectsMessage_FieldNumber_SinceTimestampMsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(POGOGetMapObjectsMessage__storage_, sinceTimestampMsArray),
        .flags = GPBFieldRepeated | GPBFieldPacked,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "latitude",
        .dataTypeSpecific.className = NULL,
        .number = POGOGetMapObjectsMessage_FieldNumber_Latitude,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(POGOGetMapObjectsMessage__storage_, latitude),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "longitude",
        .dataTypeSpecific.className = NULL,
        .number = POGOGetMapObjectsMessage_FieldNumber_Longitude,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(POGOGetMapObjectsMessage__storage_, longitude),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[POGOGetMapObjectsMessage class]
                                     rootClass:[POGOGetMapObjectsMessageRoot class]
                                          file:POGOGetMapObjectsMessageRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(POGOGetMapObjectsMessage__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
