// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/DiskEncounterResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Networking/Responses/DiskEncounterResponse.pbobjc.h"
 #import "POGOProtos/Data/PokemonData.pbobjc.h"
 #import "POGOProtos/Data/Capture/CaptureProbability.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - POGODiskEncounterResponseRoot

@implementation POGODiskEncounterResponseRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[POGOPokemonDataRoot extensionRegistry]];
    [registry addExtensions:[POGOCaptureProbabilityRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - POGODiskEncounterResponseRoot_FileDescriptor

static GPBFileDescriptor *POGODiskEncounterResponseRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Networking.Responses"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - POGODiskEncounterResponse

@implementation POGODiskEncounterResponse

@dynamic result;
@dynamic hasPokemonData, pokemonData;
@dynamic hasCaptureProbability, captureProbability;

typedef struct POGODiskEncounterResponse__storage_ {
  uint32_t _has_storage_[1];
  POGODiskEncounterResponse_Result result;
  POGOPokemonData *pokemonData;
  POGOCaptureProbability *captureProbability;
} POGODiskEncounterResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "result",
        .dataTypeSpecific.enumDescFunc = POGODiskEncounterResponse_Result_EnumDescriptor,
        .number = POGODiskEncounterResponse_FieldNumber_Result,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(POGODiskEncounterResponse__storage_, result),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "pokemonData",
        .dataTypeSpecific.className = GPBStringifySymbol(POGOPokemonData),
        .number = POGODiskEncounterResponse_FieldNumber_PokemonData,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(POGODiskEncounterResponse__storage_, pokemonData),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "captureProbability",
        .dataTypeSpecific.className = GPBStringifySymbol(POGOCaptureProbability),
        .number = POGODiskEncounterResponse_FieldNumber_CaptureProbability,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(POGODiskEncounterResponse__storage_, captureProbability),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[POGODiskEncounterResponse class]
                                     rootClass:[POGODiskEncounterResponseRoot class]
                                          file:POGODiskEncounterResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(POGODiskEncounterResponse__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t POGODiskEncounterResponse_Result_RawValue(POGODiskEncounterResponse *message) {
  GPBDescriptor *descriptor = [POGODiskEncounterResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGODiskEncounterResponse_FieldNumber_Result];
  return GPBGetMessageInt32Field(message, field);
}

void SetPOGODiskEncounterResponse_Result_RawValue(POGODiskEncounterResponse *message, int32_t value) {
  GPBDescriptor *descriptor = [POGODiskEncounterResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGODiskEncounterResponse_FieldNumber_Result];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - Enum POGODiskEncounterResponse_Result

GPBEnumDescriptor *POGODiskEncounterResponse_Result_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Unknown\000Success\000NotAvailable\000NotInRange\000"
        "EncounterAlreadyFinished\000PokemonInventor"
        "yFull\000";
    static const int32_t values[] = {
        POGODiskEncounterResponse_Result_Unknown,
        POGODiskEncounterResponse_Result_Success,
        POGODiskEncounterResponse_Result_NotAvailable,
        POGODiskEncounterResponse_Result_NotInRange,
        POGODiskEncounterResponse_Result_EncounterAlreadyFinished,
        POGODiskEncounterResponse_Result_PokemonInventoryFull,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(POGODiskEncounterResponse_Result)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:POGODiskEncounterResponse_Result_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL POGODiskEncounterResponse_Result_IsValidValue(int32_t value__) {
  switch (value__) {
    case POGODiskEncounterResponse_Result_Unknown:
    case POGODiskEncounterResponse_Result_Success:
    case POGODiskEncounterResponse_Result_NotAvailable:
    case POGODiskEncounterResponse_Result_NotInRange:
    case POGODiskEncounterResponse_Result_EncounterAlreadyFinished:
    case POGODiskEncounterResponse_Result_PokemonInventoryFull:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
