// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/FortDeployPokemonResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class POGOFortDetailsResponse;
@class POGOGymState;
@class POGOPokemonData;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum POGOFortDeployPokemonResponse_Result

typedef GPB_ENUM(POGOFortDeployPokemonResponse_Result) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  POGOFortDeployPokemonResponse_Result_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  POGOFortDeployPokemonResponse_Result_NoResultSet = 0,
  POGOFortDeployPokemonResponse_Result_Success = 1,
  POGOFortDeployPokemonResponse_Result_ErrorAlreadyHasPokemonOnFort = 2,
  POGOFortDeployPokemonResponse_Result_ErrorOpposingTeamOwnsFort = 3,
  POGOFortDeployPokemonResponse_Result_ErrorFortIsFull = 4,
  POGOFortDeployPokemonResponse_Result_ErrorNotInRange = 5,
  POGOFortDeployPokemonResponse_Result_ErrorPlayerHasNoTeam = 6,
  POGOFortDeployPokemonResponse_Result_ErrorPokemonNotFullHp = 7,
  POGOFortDeployPokemonResponse_Result_ErrorPlayerBelowMinimumLevel = 8,
};

GPBEnumDescriptor *POGOFortDeployPokemonResponse_Result_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL POGOFortDeployPokemonResponse_Result_IsValidValue(int32_t value);

#pragma mark - POGOFortDeployPokemonResponseRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface POGOFortDeployPokemonResponseRoot : GPBRootObject
@end

#pragma mark - POGOFortDeployPokemonResponse

typedef GPB_ENUM(POGOFortDeployPokemonResponse_FieldNumber) {
  POGOFortDeployPokemonResponse_FieldNumber_Result = 1,
  POGOFortDeployPokemonResponse_FieldNumber_FortDetails = 2,
  POGOFortDeployPokemonResponse_FieldNumber_PokemonData = 3,
  POGOFortDeployPokemonResponse_FieldNumber_GymState = 4,
};

@interface POGOFortDeployPokemonResponse : GPBMessage

@property(nonatomic, readwrite) POGOFortDeployPokemonResponse_Result result;

@property(nonatomic, readwrite, strong, null_resettable) POGOFortDetailsResponse *fortDetails;
/// Test to see if @c fortDetails has been set.
@property(nonatomic, readwrite) BOOL hasFortDetails;

@property(nonatomic, readwrite, strong, null_resettable) POGOPokemonData *pokemonData;
/// Test to see if @c pokemonData has been set.
@property(nonatomic, readwrite) BOOL hasPokemonData;

@property(nonatomic, readwrite, strong, null_resettable) POGOGymState *gymState;
/// Test to see if @c gymState has been set.
@property(nonatomic, readwrite) BOOL hasGymState;

@end

/// Fetches the raw value of a @c POGOFortDeployPokemonResponse's @c result property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t POGOFortDeployPokemonResponse_Result_RawValue(POGOFortDeployPokemonResponse *message);
/// Sets the raw value of an @c POGOFortDeployPokemonResponse's @c result property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetPOGOFortDeployPokemonResponse_Result_RawValue(POGOFortDeployPokemonResponse *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
