// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/FortRecallPokemonResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class POGOFortDetailsResponse;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum POGOFortRecallPokemonResponse_Result

typedef GPB_ENUM(POGOFortRecallPokemonResponse_Result) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  POGOFortRecallPokemonResponse_Result_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  POGOFortRecallPokemonResponse_Result_NoResultSet = 0,
  POGOFortRecallPokemonResponse_Result_Success = 1,
  POGOFortRecallPokemonResponse_Result_ErrorNotInRange = 2,
  POGOFortRecallPokemonResponse_Result_ErrorPokemonNotOnFort = 3,
  POGOFortRecallPokemonResponse_Result_ErrorNoPlayer = 4,
};

GPBEnumDescriptor *POGOFortRecallPokemonResponse_Result_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL POGOFortRecallPokemonResponse_Result_IsValidValue(int32_t value);

#pragma mark - POGOFortRecallPokemonResponseRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface POGOFortRecallPokemonResponseRoot : GPBRootObject
@end

#pragma mark - POGOFortRecallPokemonResponse

typedef GPB_ENUM(POGOFortRecallPokemonResponse_FieldNumber) {
  POGOFortRecallPokemonResponse_FieldNumber_Result = 1,
  POGOFortRecallPokemonResponse_FieldNumber_FortDetails = 2,
};

@interface POGOFortRecallPokemonResponse : GPBMessage

@property(nonatomic, readwrite) POGOFortRecallPokemonResponse_Result result;

@property(nonatomic, readwrite, strong, null_resettable) POGOFortDetailsResponse *fortDetails;
/// Test to see if @c fortDetails has been set.
@property(nonatomic, readwrite) BOOL hasFortDetails;

@end

/// Fetches the raw value of a @c POGOFortRecallPokemonResponse's @c result property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t POGOFortRecallPokemonResponse_Result_RawValue(POGOFortRecallPokemonResponse *message);
/// Sets the raw value of an @c POGOFortRecallPokemonResponse's @c result property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetPOGOFortRecallPokemonResponse_Result_RawValue(POGOFortRecallPokemonResponse *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
