// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/GetHatchedEggsResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - POGOGetHatchedEggsResponseRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface POGOGetHatchedEggsResponseRoot : GPBRootObject
@end

#pragma mark - POGOGetHatchedEggsResponse

typedef GPB_ENUM(POGOGetHatchedEggsResponse_FieldNumber) {
  POGOGetHatchedEggsResponse_FieldNumber_Success = 1,
  POGOGetHatchedEggsResponse_FieldNumber_PokemonIdArray = 2,
  POGOGetHatchedEggsResponse_FieldNumber_ExperienceAwardedArray = 3,
  POGOGetHatchedEggsResponse_FieldNumber_CandyAwardedArray = 4,
  POGOGetHatchedEggsResponse_FieldNumber_StardustAwardedArray = 5,
};

@interface POGOGetHatchedEggsResponse : GPBMessage

@property(nonatomic, readwrite) BOOL success;

@property(nonatomic, readwrite, strong, null_resettable) GPBUInt64Array *pokemonIdArray;
/// The number of items in @c pokemonIdArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger pokemonIdArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *experienceAwardedArray;
/// The number of items in @c experienceAwardedArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger experienceAwardedArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *candyAwardedArray;
/// The number of items in @c candyAwardedArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger candyAwardedArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *stardustAwardedArray;
/// The number of items in @c stardustAwardedArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger stardustAwardedArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
