// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/GetMapObjectsResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Networking/Responses/GetMapObjectsResponse.pbobjc.h"
 #import "POGOProtos/Map/MapCell.pbobjc.h"
 #import "POGOProtos/Map/MapObjectsStatus.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - POGOGetMapObjectsResponseRoot

@implementation POGOGetMapObjectsResponseRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[POGOMapCellRoot extensionRegistry]];
    [registry addExtensions:[POGOMapObjectsStatusRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - POGOGetMapObjectsResponseRoot_FileDescriptor

static GPBFileDescriptor *POGOGetMapObjectsResponseRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Networking.Responses"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - POGOGetMapObjectsResponse

@implementation POGOGetMapObjectsResponse

@dynamic mapCellsArray, mapCellsArray_Count;
@dynamic status;

typedef struct POGOGetMapObjectsResponse__storage_ {
  uint32_t _has_storage_[1];
  POGOMapObjectsStatus status;
  NSMutableArray *mapCellsArray;
} POGOGetMapObjectsResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "mapCellsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(POGOMapCell),
        .number = POGOGetMapObjectsResponse_FieldNumber_MapCellsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(POGOGetMapObjectsResponse__storage_, mapCellsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "status",
        .dataTypeSpecific.enumDescFunc = POGOMapObjectsStatus_EnumDescriptor,
        .number = POGOGetMapObjectsResponse_FieldNumber_Status,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(POGOGetMapObjectsResponse__storage_, status),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[POGOGetMapObjectsResponse class]
                                     rootClass:[POGOGetMapObjectsResponseRoot class]
                                          file:POGOGetMapObjectsResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(POGOGetMapObjectsResponse__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t POGOGetMapObjectsResponse_Status_RawValue(POGOGetMapObjectsResponse *message) {
  GPBDescriptor *descriptor = [POGOGetMapObjectsResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGOGetMapObjectsResponse_FieldNumber_Status];
  return GPBGetMessageInt32Field(message, field);
}

void SetPOGOGetMapObjectsResponse_Status_RawValue(POGOGetMapObjectsResponse *message, int32_t value) {
  GPBDescriptor *descriptor = [POGOGetMapObjectsResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGOGetMapObjectsResponse_FieldNumber_Status];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
