// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Map/Pokemon/WildPokemon.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Map/Pokemon/WildPokemon.pbobjc.h"
 #import "POGOProtos/Data/PokemonData.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - POGOWildPokemonRoot

@implementation POGOWildPokemonRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[POGOPokemonDataRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - POGOWildPokemonRoot_FileDescriptor

static GPBFileDescriptor *POGOWildPokemonRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Map.Pokemon"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - POGOWildPokemon

@implementation POGOWildPokemon

@dynamic encounterId;
@dynamic lastModifiedTimestampMs;
@dynamic latitude;
@dynamic longitude;
@dynamic spawnPointId;
@dynamic hasPokemonData, pokemonData;
@dynamic timeTillHiddenMs;

typedef struct POGOWildPokemon__storage_ {
  uint32_t _has_storage_[1];
  int32_t timeTillHiddenMs;
  NSString *spawnPointId;
  POGOPokemonData *pokemonData;
  uint64_t encounterId;
  int64_t lastModifiedTimestampMs;
  double latitude;
  double longitude;
} POGOWildPokemon__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "encounterId",
        .dataTypeSpecific.className = NULL,
        .number = POGOWildPokemon_FieldNumber_EncounterId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(POGOWildPokemon__storage_, encounterId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFixed64,
      },
      {
        .name = "lastModifiedTimestampMs",
        .dataTypeSpecific.className = NULL,
        .number = POGOWildPokemon_FieldNumber_LastModifiedTimestampMs,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(POGOWildPokemon__storage_, lastModifiedTimestampMs),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "latitude",
        .dataTypeSpecific.className = NULL,
        .number = POGOWildPokemon_FieldNumber_Latitude,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(POGOWildPokemon__storage_, latitude),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "longitude",
        .dataTypeSpecific.className = NULL,
        .number = POGOWildPokemon_FieldNumber_Longitude,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(POGOWildPokemon__storage_, longitude),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "spawnPointId",
        .dataTypeSpecific.className = NULL,
        .number = POGOWildPokemon_FieldNumber_SpawnPointId,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(POGOWildPokemon__storage_, spawnPointId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "pokemonData",
        .dataTypeSpecific.className = GPBStringifySymbol(POGOPokemonData),
        .number = POGOWildPokemon_FieldNumber_PokemonData,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(POGOWildPokemon__storage_, pokemonData),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "timeTillHiddenMs",
        .dataTypeSpecific.className = NULL,
        .number = POGOWildPokemon_FieldNumber_TimeTillHiddenMs,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(POGOWildPokemon__storage_, timeTillHiddenMs),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[POGOWildPokemon class]
                                     rootClass:[POGOWildPokemonRoot class]
                                          file:POGOWildPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(POGOWildPokemon__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
