// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Data/Player/EquippedBadge.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Data/Player/EquippedBadge.pbobjc.h"
 #import "POGOProtos/Enums/BadgeType.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - POGOEquippedBadgeRoot

@implementation POGOEquippedBadgeRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[POGOBadgeTypeRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - POGOEquippedBadgeRoot_FileDescriptor

static GPBFileDescriptor *POGOEquippedBadgeRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Data.Player"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - POGOEquippedBadge

@implementation POGOEquippedBadge

@dynamic badgeType;
@dynamic level;
@dynamic nextEquipChangeAllowedTimestampMs;

typedef struct POGOEquippedBadge__storage_ {
  uint32_t _has_storage_[1];
  POGOBadgeType badgeType;
  int32_t level;
  int64_t nextEquipChangeAllowedTimestampMs;
} POGOEquippedBadge__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "badgeType",
        .dataTypeSpecific.enumDescFunc = POGOBadgeType_EnumDescriptor,
        .number = POGOEquippedBadge_FieldNumber_BadgeType,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(POGOEquippedBadge__storage_, badgeType),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "level",
        .dataTypeSpecific.className = NULL,
        .number = POGOEquippedBadge_FieldNumber_Level,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(POGOEquippedBadge__storage_, level),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "nextEquipChangeAllowedTimestampMs",
        .dataTypeSpecific.className = NULL,
        .number = POGOEquippedBadge_FieldNumber_NextEquipChangeAllowedTimestampMs,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(POGOEquippedBadge__storage_, nextEquipChangeAllowedTimestampMs),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[POGOEquippedBadge class]
                                     rootClass:[POGOEquippedBadgeRoot class]
                                          file:POGOEquippedBadgeRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(POGOEquippedBadge__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t POGOEquippedBadge_BadgeType_RawValue(POGOEquippedBadge *message) {
  GPBDescriptor *descriptor = [POGOEquippedBadge descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGOEquippedBadge_FieldNumber_BadgeType];
  return GPBGetMessageInt32Field(message, field);
}

void SetPOGOEquippedBadge_BadgeType_RawValue(POGOEquippedBadge *message, int32_t value) {
  GPBDescriptor *descriptor = [POGOEquippedBadge descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGOEquippedBadge_FieldNumber_BadgeType];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
