// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Data/Player/PlayerPublicProfile.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Data/Player/PlayerPublicProfile.pbobjc.h"
 #import "POGOProtos/Data/Player/PlayerAvatar.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - POGOPlayerPublicProfileRoot

@implementation POGOPlayerPublicProfileRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[POGOPlayerAvatarRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - POGOPlayerPublicProfileRoot_FileDescriptor

static GPBFileDescriptor *POGOPlayerPublicProfileRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Data.Player"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - POGOPlayerPublicProfile

@implementation POGOPlayerPublicProfile

@dynamic name;
@dynamic level;
@dynamic hasAvatar, avatar;

typedef struct POGOPlayerPublicProfile__storage_ {
  uint32_t _has_storage_[1];
  int32_t level;
  NSString *name;
  POGOPlayerAvatar *avatar;
} POGOPlayerPublicProfile__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "name",
        .dataTypeSpecific.className = NULL,
        .number = POGOPlayerPublicProfile_FieldNumber_Name,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(POGOPlayerPublicProfile__storage_, name),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "level",
        .dataTypeSpecific.className = NULL,
        .number = POGOPlayerPublicProfile_FieldNumber_Level,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(POGOPlayerPublicProfile__storage_, level),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "avatar",
        .dataTypeSpecific.className = GPBStringifySymbol(POGOPlayerAvatar),
        .number = POGOPlayerPublicProfile_FieldNumber_Avatar,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(POGOPlayerPublicProfile__storage_, avatar),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[POGOPlayerPublicProfile class]
                                     rootClass:[POGOPlayerPublicProfileRoot class]
                                          file:POGOPlayerPublicProfileRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(POGOPlayerPublicProfile__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
