// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Settings/Master/CameraSettings.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - POGOCameraSettingsRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface POGOCameraSettingsRoot : GPBRootObject
@end

#pragma mark - POGOCameraSettings

typedef GPB_ENUM(POGOCameraSettings_FieldNumber) {
  POGOCameraSettings_FieldNumber_NextCamera = 1,
  POGOCameraSettings_FieldNumber_InterpolationArray = 2,
  POGOCameraSettings_FieldNumber_TargetTypeArray = 3,
  POGOCameraSettings_FieldNumber_EaseInSpeedArray = 4,
  POGOCameraSettings_FieldNumber_EastOutSpeedArray = 5,
  POGOCameraSettings_FieldNumber_DurationSecondsArray = 6,
  POGOCameraSettings_FieldNumber_WaitSecondsArray = 7,
  POGOCameraSettings_FieldNumber_TransitionSecondsArray = 8,
  POGOCameraSettings_FieldNumber_AngleDegreeArray = 9,
  POGOCameraSettings_FieldNumber_AngleOffsetDegreeArray = 10,
  POGOCameraSettings_FieldNumber_PitchDegreeArray = 11,
  POGOCameraSettings_FieldNumber_PitchOffsetDegreeArray = 12,
  POGOCameraSettings_FieldNumber_RollDegreeArray = 13,
  POGOCameraSettings_FieldNumber_DistanceMetersArray = 14,
  POGOCameraSettings_FieldNumber_HeightPercentArray = 15,
  POGOCameraSettings_FieldNumber_VertCtrRatioArray = 16,
};

@interface POGOCameraSettings : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *nextCamera;

// |interpolationArray| contains |POGOCameraInterpolation|
@property(nonatomic, readwrite, strong, null_resettable) GPBEnumArray *interpolationArray;
/// The number of items in @c interpolationArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger interpolationArray_Count;

// |targetTypeArray| contains |POGOCameraTarget|
@property(nonatomic, readwrite, strong, null_resettable) GPBEnumArray *targetTypeArray;
/// The number of items in @c targetTypeArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger targetTypeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBFloatArray *easeInSpeedArray;
/// The number of items in @c easeInSpeedArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger easeInSpeedArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBFloatArray *eastOutSpeedArray;
/// The number of items in @c eastOutSpeedArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger eastOutSpeedArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBFloatArray *durationSecondsArray;
/// The number of items in @c durationSecondsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger durationSecondsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBFloatArray *waitSecondsArray;
/// The number of items in @c waitSecondsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger waitSecondsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBFloatArray *transitionSecondsArray;
/// The number of items in @c transitionSecondsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger transitionSecondsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBFloatArray *angleDegreeArray;
/// The number of items in @c angleDegreeArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger angleDegreeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBFloatArray *angleOffsetDegreeArray;
/// The number of items in @c angleOffsetDegreeArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger angleOffsetDegreeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBFloatArray *pitchDegreeArray;
/// The number of items in @c pitchDegreeArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger pitchDegreeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBFloatArray *pitchOffsetDegreeArray;
/// The number of items in @c pitchOffsetDegreeArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger pitchOffsetDegreeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBFloatArray *rollDegreeArray;
/// The number of items in @c rollDegreeArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger rollDegreeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBFloatArray *distanceMetersArray;
/// The number of items in @c distanceMetersArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger distanceMetersArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBFloatArray *heightPercentArray;
/// The number of items in @c heightPercentArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger heightPercentArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBFloatArray *vertCtrRatioArray;
/// The number of items in @c vertCtrRatioArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger vertCtrRatioArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
