// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Requests/RequestType.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum POGORequestType

typedef GPB_ENUM(POGORequestType) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  POGORequestType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /// No implementation required
  POGORequestType_MethodUnset = 0,

  /// Implemented [R & M]
  POGORequestType_PlayerUpdate = 1,

  /// Implemented [R & M]
  POGORequestType_GetPlayer = 2,

  /// Implemented [R & M]
  POGORequestType_GetInventory = 4,

  /// Implemented [R & M]
  POGORequestType_DownloadSettings = 5,

  /// Implemented [R & M]
  POGORequestType_DownloadItemTemplates = 6,

  /// Implemented [R & M]
  POGORequestType_DownloadRemoteConfigVersion = 7,

  /// Implemented [R & M]
  POGORequestType_FortSearch = 101,

  /// Implemented [R & M]
  POGORequestType_Encounter = 102,

  /// Implemented [R & M]
  POGORequestType_CatchPokemon = 103,

  /// Implemented [R & M]
  POGORequestType_FortDetails = 104,

  /// Can't find this one
  POGORequestType_ItemUse = 105,

  /// Implemented [R & M]
  POGORequestType_GetMapObjects = 106,

  /// Implemented [R & M]
  POGORequestType_FortDeployPokemon = 110,

  /// Implemented [R & M]
  POGORequestType_FortRecallPokemon = 111,

  /// Implemented [R & M]
  POGORequestType_ReleasePokemon = 112,

  /// Implemented [R & M]
  POGORequestType_UseItemPotion = 113,

  /// Implemented [R & M]
  POGORequestType_UseItemCapture = 114,

  /// Can't find this one
  POGORequestType_UseItemFlee = 115,

  /// Implemented [R & M]
  POGORequestType_UseItemRevive = 116,

  /// Not yet implemented in the game
  POGORequestType_TradeSearch = 117,

  /// Not yet implemented in the game
  POGORequestType_TradeOffer = 118,

  /// Not yet implemented in the game
  POGORequestType_TradeResponse = 119,

  /// Not yet implemented in the game
  POGORequestType_TradeResult = 120,

  /// Implemented [R & M]
  POGORequestType_GetPlayerProfile = 121,

  /// Can't find this one
  POGORequestType_GetItemPack = 122,

  /// Can't find this one
  POGORequestType_BuyItemPack = 123,

  /// Can't find this one
  POGORequestType_BuyGemPack = 124,

  /// Implemented [R & M]
  POGORequestType_EvolvePokemon = 125,

  /// Implemented [R & M]
  POGORequestType_GetHatchedEggs = 126,

  /// Implemented [R & M]
  POGORequestType_EncounterTutorialComplete = 127,

  /// Implemented [R & M]
  POGORequestType_LevelUpRewards = 128,

  /// Implemented [R & M]
  POGORequestType_CheckAwardedBadges = 129,

  /// Implemented [R & M]
  POGORequestType_UseItemGym = 133,

  /// Implemented [R & M]
  POGORequestType_GetGymDetails = 134,

  /// Implemented [R & M]
  POGORequestType_StartGymBattle = 135,

  /// Implemented [R & M]
  POGORequestType_AttackGym = 136,

  /// Implemented [R & M]
  POGORequestType_RecycleInventoryItem = 137,

  /// Implemented [R & M]
  POGORequestType_CollectDailyBonus = 138,

  /// Implemented [R & M]
  POGORequestType_UseItemXpBoost = 139,

  /// Implemented [R & M]
  POGORequestType_UseItemEggIncubator = 140,

  /// Implemented [R & M]
  POGORequestType_UseIncense = 141,

  /// Implemented [R & M]
  POGORequestType_GetIncensePokemon = 142,

  /// Implemented [R & M]
  POGORequestType_IncenseEncounter = 143,

  /// Implemented [R & M]
  POGORequestType_AddFortModifier = 144,

  /// Implemented [R & M]
  POGORequestType_DiskEncounter = 145,

  /// Implemented [R & M]
  POGORequestType_CollectDailyDefenderBonus = 146,

  /// Implemented [R & M]
  POGORequestType_UpgradePokemon = 147,

  /// Implemented [R & M]
  POGORequestType_SetFavoritePokemon = 148,

  /// Implemented [R & M]
  POGORequestType_NicknamePokemon = 149,

  /// Implemented [R & M]
  POGORequestType_EquipBadge = 150,

  /// Implemented [R & M]
  POGORequestType_SetContactSettings = 151,

  /// Implemented [R & M]
  POGORequestType_GetAssetDigest = 300,

  /// Implemented [R & M]
  POGORequestType_GetDownloadUrls = 301,

  /// Implemented [R & M]
  POGORequestType_GetSuggestedCodenames = 401,

  /// Implemented [R & M] TEST RESPONSE
  POGORequestType_CheckCodenameAvailable = 402,

  /// Implemented [R & M] TEST RESPONSE
  POGORequestType_ClaimCodename = 403,

  /// Implemented [R & M]
  POGORequestType_SetAvatar = 404,

  /// Implemented [R & M]
  POGORequestType_SetPlayerTeam = 405,

  /// Implemented [R & M]
  POGORequestType_MarkTutorialComplete = 406,

  /// Can't find this one
  POGORequestType_LoadSpawnPoints = 500,

  /// Implemented [R & M]
  POGORequestType_Echo = 666,
  POGORequestType_DebugUpdateInventory = 700,
  POGORequestType_DebugDeletePlayer = 701,

  /// Not yet released.
  POGORequestType_SfidaRegistration = 800,

  /// Implemented [R & M]
  POGORequestType_SfidaActionLog = 801,

  /// Not yet released.
  POGORequestType_SfidaCertification = 802,

  /// Not yet released.
  POGORequestType_SfidaUpdate = 803,

  /// Not yet released.
  POGORequestType_SfidaAction = 804,

  /// Not yet released.
  POGORequestType_SfidaDowser = 805,

  /// Not yet released.
  POGORequestType_SfidaCapture = 806,
};

GPBEnumDescriptor *POGORequestType_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL POGORequestType_IsValidValue(int32_t value);

#pragma mark - POGORequestTypeRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface POGORequestTypeRoot : GPBRootObject
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
