// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/CheckCodenameAvailableResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Networking/Responses/CheckCodenameAvailableResponse.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - POGOCheckCodenameAvailableResponseRoot

@implementation POGOCheckCodenameAvailableResponseRoot

@end

#pragma mark - POGOCheckCodenameAvailableResponseRoot_FileDescriptor

static GPBFileDescriptor *POGOCheckCodenameAvailableResponseRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Networking.Responses"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - POGOCheckCodenameAvailableResponse

@implementation POGOCheckCodenameAvailableResponse

@dynamic codename;
@dynamic userMessage;
@dynamic isAssignable;
@dynamic status;

typedef struct POGOCheckCodenameAvailableResponse__storage_ {
  uint32_t _has_storage_[1];
  POGOCheckCodenameAvailableResponse_Status status;
  NSString *codename;
  NSString *userMessage;
} POGOCheckCodenameAvailableResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "codename",
        .dataTypeSpecific.className = NULL,
        .number = POGOCheckCodenameAvailableResponse_FieldNumber_Codename,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(POGOCheckCodenameAvailableResponse__storage_, codename),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "userMessage",
        .dataTypeSpecific.className = NULL,
        .number = POGOCheckCodenameAvailableResponse_FieldNumber_UserMessage,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(POGOCheckCodenameAvailableResponse__storage_, userMessage),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "isAssignable",
        .dataTypeSpecific.className = NULL,
        .number = POGOCheckCodenameAvailableResponse_FieldNumber_IsAssignable,
        .hasIndex = 2,
        .offset = 3,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "status",
        .dataTypeSpecific.enumDescFunc = POGOCheckCodenameAvailableResponse_Status_EnumDescriptor,
        .number = POGOCheckCodenameAvailableResponse_FieldNumber_Status,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(POGOCheckCodenameAvailableResponse__storage_, status),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[POGOCheckCodenameAvailableResponse class]
                                     rootClass:[POGOCheckCodenameAvailableResponseRoot class]
                                          file:POGOCheckCodenameAvailableResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(POGOCheckCodenameAvailableResponse__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t POGOCheckCodenameAvailableResponse_Status_RawValue(POGOCheckCodenameAvailableResponse *message) {
  GPBDescriptor *descriptor = [POGOCheckCodenameAvailableResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGOCheckCodenameAvailableResponse_FieldNumber_Status];
  return GPBGetMessageInt32Field(message, field);
}

void SetPOGOCheckCodenameAvailableResponse_Status_RawValue(POGOCheckCodenameAvailableResponse *message, int32_t value) {
  GPBDescriptor *descriptor = [POGOCheckCodenameAvailableResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGOCheckCodenameAvailableResponse_FieldNumber_Status];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - Enum POGOCheckCodenameAvailableResponse_Status

GPBEnumDescriptor *POGOCheckCodenameAvailableResponse_Status_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Unset\000Success\000CodenameNotAvailable\000Coden"
        "ameNotValid\000CurrentOwner\000CodenameChangeN"
        "otAllowed\000";
    static const int32_t values[] = {
        POGOCheckCodenameAvailableResponse_Status_Unset,
        POGOCheckCodenameAvailableResponse_Status_Success,
        POGOCheckCodenameAvailableResponse_Status_CodenameNotAvailable,
        POGOCheckCodenameAvailableResponse_Status_CodenameNotValid,
        POGOCheckCodenameAvailableResponse_Status_CurrentOwner,
        POGOCheckCodenameAvailableResponse_Status_CodenameChangeNotAllowed,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(POGOCheckCodenameAvailableResponse_Status)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:POGOCheckCodenameAvailableResponse_Status_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL POGOCheckCodenameAvailableResponse_Status_IsValidValue(int32_t value__) {
  switch (value__) {
    case POGOCheckCodenameAvailableResponse_Status_Unset:
    case POGOCheckCodenameAvailableResponse_Status_Success:
    case POGOCheckCodenameAvailableResponse_Status_CodenameNotAvailable:
    case POGOCheckCodenameAvailableResponse_Status_CodenameNotValid:
    case POGOCheckCodenameAvailableResponse_Status_CurrentOwner:
    case POGOCheckCodenameAvailableResponse_Status_CodenameChangeNotAllowed:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
