// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/CollectDailyDefenderBonusResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum POGOCollectDailyDefenderBonusResponse_Result

typedef GPB_ENUM(POGOCollectDailyDefenderBonusResponse_Result) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  POGOCollectDailyDefenderBonusResponse_Result_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  POGOCollectDailyDefenderBonusResponse_Result_Unset = 0,
  POGOCollectDailyDefenderBonusResponse_Result_Success = 1,
  POGOCollectDailyDefenderBonusResponse_Result_Failure = 2,
  POGOCollectDailyDefenderBonusResponse_Result_TooSoon = 3,
  POGOCollectDailyDefenderBonusResponse_Result_NoDefenders = 4,
};

GPBEnumDescriptor *POGOCollectDailyDefenderBonusResponse_Result_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL POGOCollectDailyDefenderBonusResponse_Result_IsValidValue(int32_t value);

#pragma mark - POGOCollectDailyDefenderBonusResponseRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface POGOCollectDailyDefenderBonusResponseRoot : GPBRootObject
@end

#pragma mark - POGOCollectDailyDefenderBonusResponse

typedef GPB_ENUM(POGOCollectDailyDefenderBonusResponse_FieldNumber) {
  POGOCollectDailyDefenderBonusResponse_FieldNumber_Result = 1,
  POGOCollectDailyDefenderBonusResponse_FieldNumber_CurrencyTypeArray = 2,
  POGOCollectDailyDefenderBonusResponse_FieldNumber_CurrencyAwardedArray = 3,
  POGOCollectDailyDefenderBonusResponse_FieldNumber_DefendersCount = 4,
};

@interface POGOCollectDailyDefenderBonusResponse : GPBMessage

@property(nonatomic, readwrite) POGOCollectDailyDefenderBonusResponse_Result result;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *currencyTypeArray;
/// The number of items in @c currencyTypeArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger currencyTypeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *currencyAwardedArray;
/// The number of items in @c currencyAwardedArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger currencyAwardedArray_Count;

@property(nonatomic, readwrite) int32_t defendersCount;

@end

/// Fetches the raw value of a @c POGOCollectDailyDefenderBonusResponse's @c result property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t POGOCollectDailyDefenderBonusResponse_Result_RawValue(POGOCollectDailyDefenderBonusResponse *message);
/// Sets the raw value of an @c POGOCollectDailyDefenderBonusResponse's @c result property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetPOGOCollectDailyDefenderBonusResponse_Result_RawValue(POGOCollectDailyDefenderBonusResponse *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
