// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/GetGymDetailsResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Networking/Responses/GetGymDetailsResponse.pbobjc.h"
 #import "POGOProtos/Data/Gym/GymState.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - POGOGetGymDetailsResponseRoot

@implementation POGOGetGymDetailsResponseRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[POGOGymStateRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - POGOGetGymDetailsResponseRoot_FileDescriptor

static GPBFileDescriptor *POGOGetGymDetailsResponseRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Networking.Responses"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - POGOGetGymDetailsResponse

@implementation POGOGetGymDetailsResponse

@dynamic hasGymState, gymState;
@dynamic name;
@dynamic urlsArray, urlsArray_Count;
@dynamic result;
@dynamic description_p;

typedef struct POGOGetGymDetailsResponse__storage_ {
  uint32_t _has_storage_[1];
  POGOGetGymDetailsResponse_Result result;
  POGOGymState *gymState;
  NSString *name;
  NSMutableArray *urlsArray;
  NSString *description_p;
} POGOGetGymDetailsResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "gymState",
        .dataTypeSpecific.className = GPBStringifySymbol(POGOGymState),
        .number = POGOGetGymDetailsResponse_FieldNumber_GymState,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(POGOGetGymDetailsResponse__storage_, gymState),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "name",
        .dataTypeSpecific.className = NULL,
        .number = POGOGetGymDetailsResponse_FieldNumber_Name,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(POGOGetGymDetailsResponse__storage_, name),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "urlsArray",
        .dataTypeSpecific.className = NULL,
        .number = POGOGetGymDetailsResponse_FieldNumber_UrlsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(POGOGetGymDetailsResponse__storage_, urlsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "result",
        .dataTypeSpecific.enumDescFunc = POGOGetGymDetailsResponse_Result_EnumDescriptor,
        .number = POGOGetGymDetailsResponse_FieldNumber_Result,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(POGOGetGymDetailsResponse__storage_, result),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "description_p",
        .dataTypeSpecific.className = NULL,
        .number = POGOGetGymDetailsResponse_FieldNumber_Description_p,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(POGOGetGymDetailsResponse__storage_, description_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[POGOGetGymDetailsResponse class]
                                     rootClass:[POGOGetGymDetailsResponseRoot class]
                                          file:POGOGetGymDetailsResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(POGOGetGymDetailsResponse__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t POGOGetGymDetailsResponse_Result_RawValue(POGOGetGymDetailsResponse *message) {
  GPBDescriptor *descriptor = [POGOGetGymDetailsResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGOGetGymDetailsResponse_FieldNumber_Result];
  return GPBGetMessageInt32Field(message, field);
}

void SetPOGOGetGymDetailsResponse_Result_RawValue(POGOGetGymDetailsResponse *message, int32_t value) {
  GPBDescriptor *descriptor = [POGOGetGymDetailsResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGOGetGymDetailsResponse_FieldNumber_Result];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - Enum POGOGetGymDetailsResponse_Result

GPBEnumDescriptor *POGOGetGymDetailsResponse_Result_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Unset\000Success\000ErrorNotInRange\000";
    static const int32_t values[] = {
        POGOGetGymDetailsResponse_Result_Unset,
        POGOGetGymDetailsResponse_Result_Success,
        POGOGetGymDetailsResponse_Result_ErrorNotInRange,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(POGOGetGymDetailsResponse_Result)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:POGOGetGymDetailsResponse_Result_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL POGOGetGymDetailsResponse_Result_IsValidValue(int32_t value__) {
  switch (value__) {
    case POGOGetGymDetailsResponse_Result_Unset:
    case POGOGetGymDetailsResponse_Result_Success:
    case POGOGetGymDetailsResponse_Result_ErrorNotInRange:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
