// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/IncenseEncounterResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Networking/Responses/IncenseEncounterResponse.pbobjc.h"
 #import "POGOProtos/Data/PokemonData.pbobjc.h"
 #import "POGOProtos/Data/Capture/CaptureProbability.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - POGOIncenseEncounterResponseRoot

@implementation POGOIncenseEncounterResponseRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[POGOPokemonDataRoot extensionRegistry]];
    [registry addExtensions:[POGOCaptureProbabilityRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - POGOIncenseEncounterResponseRoot_FileDescriptor

static GPBFileDescriptor *POGOIncenseEncounterResponseRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Networking.Responses"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - POGOIncenseEncounterResponse

@implementation POGOIncenseEncounterResponse

@dynamic result;
@dynamic hasPokemonData, pokemonData;
@dynamic hasCaptureProbability, captureProbability;

typedef struct POGOIncenseEncounterResponse__storage_ {
  uint32_t _has_storage_[1];
  POGOIncenseEncounterResponse_Result result;
  POGOPokemonData *pokemonData;
  POGOCaptureProbability *captureProbability;
} POGOIncenseEncounterResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "result",
        .dataTypeSpecific.enumDescFunc = POGOIncenseEncounterResponse_Result_EnumDescriptor,
        .number = POGOIncenseEncounterResponse_FieldNumber_Result,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(POGOIncenseEncounterResponse__storage_, result),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "pokemonData",
        .dataTypeSpecific.className = GPBStringifySymbol(POGOPokemonData),
        .number = POGOIncenseEncounterResponse_FieldNumber_PokemonData,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(POGOIncenseEncounterResponse__storage_, pokemonData),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "captureProbability",
        .dataTypeSpecific.className = GPBStringifySymbol(POGOCaptureProbability),
        .number = POGOIncenseEncounterResponse_FieldNumber_CaptureProbability,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(POGOIncenseEncounterResponse__storage_, captureProbability),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[POGOIncenseEncounterResponse class]
                                     rootClass:[POGOIncenseEncounterResponseRoot class]
                                          file:POGOIncenseEncounterResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(POGOIncenseEncounterResponse__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t POGOIncenseEncounterResponse_Result_RawValue(POGOIncenseEncounterResponse *message) {
  GPBDescriptor *descriptor = [POGOIncenseEncounterResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGOIncenseEncounterResponse_FieldNumber_Result];
  return GPBGetMessageInt32Field(message, field);
}

void SetPOGOIncenseEncounterResponse_Result_RawValue(POGOIncenseEncounterResponse *message, int32_t value) {
  GPBDescriptor *descriptor = [POGOIncenseEncounterResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGOIncenseEncounterResponse_FieldNumber_Result];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - Enum POGOIncenseEncounterResponse_Result

GPBEnumDescriptor *POGOIncenseEncounterResponse_Result_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "IncenseEncounterUnknown\000IncenseEncounter"
        "Success\000IncenseEncounterNotAvailable\000Pok"
        "emonInventoryFull\000";
    static const int32_t values[] = {
        POGOIncenseEncounterResponse_Result_IncenseEncounterUnknown,
        POGOIncenseEncounterResponse_Result_IncenseEncounterSuccess,
        POGOIncenseEncounterResponse_Result_IncenseEncounterNotAvailable,
        POGOIncenseEncounterResponse_Result_PokemonInventoryFull,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(POGOIncenseEncounterResponse_Result)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:POGOIncenseEncounterResponse_Result_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL POGOIncenseEncounterResponse_Result_IsValidValue(int32_t value__) {
  switch (value__) {
    case POGOIncenseEncounterResponse_Result_IncenseEncounterUnknown:
    case POGOIncenseEncounterResponse_Result_IncenseEncounterSuccess:
    case POGOIncenseEncounterResponse_Result_IncenseEncounterNotAvailable:
    case POGOIncenseEncounterResponse_Result_PokemonInventoryFull:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
