// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Data/Battle/BattleActionType.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Data/Battle/BattleActionType.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - POGOBattleActionTypeRoot

@implementation POGOBattleActionTypeRoot

@end

#pragma mark - Enum POGOBattleActionType

GPBEnumDescriptor *POGOBattleActionType_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "ActionUnset\000ActionAttack\000ActionDodge\000Act"
        "ionSpecialAttack\000ActionSwapPokemon\000Actio"
        "nFaint\000ActionPlayerJoin\000ActionPlayerQuit"
        "\000ActionVictory\000ActionDefeat\000ActionTimedO"
        "ut\000";
    static const int32_t values[] = {
        POGOBattleActionType_ActionUnset,
        POGOBattleActionType_ActionAttack,
        POGOBattleActionType_ActionDodge,
        POGOBattleActionType_ActionSpecialAttack,
        POGOBattleActionType_ActionSwapPokemon,
        POGOBattleActionType_ActionFaint,
        POGOBattleActionType_ActionPlayerJoin,
        POGOBattleActionType_ActionPlayerQuit,
        POGOBattleActionType_ActionVictory,
        POGOBattleActionType_ActionDefeat,
        POGOBattleActionType_ActionTimedOut,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(POGOBattleActionType)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:POGOBattleActionType_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL POGOBattleActionType_IsValidValue(int32_t value__) {
  switch (value__) {
    case POGOBattleActionType_ActionUnset:
    case POGOBattleActionType_ActionAttack:
    case POGOBattleActionType_ActionDodge:
    case POGOBattleActionType_ActionSpecialAttack:
    case POGOBattleActionType_ActionSwapPokemon:
    case POGOBattleActionType_ActionFaint:
    case POGOBattleActionType_ActionPlayerJoin:
    case POGOBattleActionType_ActionPlayerQuit:
    case POGOBattleActionType_ActionVictory:
    case POGOBattleActionType_ActionDefeat:
    case POGOBattleActionType_ActionTimedOut:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
