// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Data/Battle/BattleLog.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class POGOBattleAction;
GPB_ENUM_FWD_DECLARE(POGOBattleState);
GPB_ENUM_FWD_DECLARE(POGOBattleType);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - POGOBattleLogRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface POGOBattleLogRoot : GPBRootObject
@end

#pragma mark - POGOBattleLog

typedef GPB_ENUM(POGOBattleLog_FieldNumber) {
  POGOBattleLog_FieldNumber_State = 1,
  POGOBattleLog_FieldNumber_BattleType = 2,
  POGOBattleLog_FieldNumber_ServerMs = 3,
  POGOBattleLog_FieldNumber_BattleActionsArray = 4,
  POGOBattleLog_FieldNumber_BattleStartTimestampMs = 5,
  POGOBattleLog_FieldNumber_BattleEndTimestampMs = 6,
};

@interface POGOBattleLog : GPBMessage

@property(nonatomic, readwrite) enum POGOBattleState state;

@property(nonatomic, readwrite) enum POGOBattleType battleType;

@property(nonatomic, readwrite) int64_t serverMs;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<POGOBattleAction*> *battleActionsArray;
/// The number of items in @c battleActionsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger battleActionsArray_Count;

@property(nonatomic, readwrite) int64_t battleStartTimestampMs;

@property(nonatomic, readwrite) int64_t battleEndTimestampMs;

@end

/// Fetches the raw value of a @c POGOBattleLog's @c state property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t POGOBattleLog_State_RawValue(POGOBattleLog *message);
/// Sets the raw value of an @c POGOBattleLog's @c state property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetPOGOBattleLog_State_RawValue(POGOBattleLog *message, int32_t value);

/// Fetches the raw value of a @c POGOBattleLog's @c battleType property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t POGOBattleLog_BattleType_RawValue(POGOBattleLog *message);
/// Sets the raw value of an @c POGOBattleLog's @c battleType property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetPOGOBattleLog_BattleType_RawValue(POGOBattleLog *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
