// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Settings/Master/BadgeSettings.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Settings/Master/BadgeSettings.pbobjc.h"
 #import "POGOProtos/Enums/BadgeType.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - POGOBadgeSettingsRoot

@implementation POGOBadgeSettingsRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[POGOBadgeTypeRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - POGOBadgeSettingsRoot_FileDescriptor

static GPBFileDescriptor *POGOBadgeSettingsRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Settings.Master"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - POGOBadgeSettings

@implementation POGOBadgeSettings

@dynamic badgeType;
@dynamic badgeRank;
@dynamic targetsArray, targetsArray_Count;

typedef struct POGOBadgeSettings__storage_ {
  uint32_t _has_storage_[1];
  POGOBadgeType badgeType;
  int32_t badgeRank;
  GPBInt32Array *targetsArray;
} POGOBadgeSettings__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "badgeType",
        .dataTypeSpecific.enumDescFunc = POGOBadgeType_EnumDescriptor,
        .number = POGOBadgeSettings_FieldNumber_BadgeType,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(POGOBadgeSettings__storage_, badgeType),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "badgeRank",
        .dataTypeSpecific.className = NULL,
        .number = POGOBadgeSettings_FieldNumber_BadgeRank,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(POGOBadgeSettings__storage_, badgeRank),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "targetsArray",
        .dataTypeSpecific.className = NULL,
        .number = POGOBadgeSettings_FieldNumber_TargetsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(POGOBadgeSettings__storage_, targetsArray),
        .flags = GPBFieldRepeated | GPBFieldPacked,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[POGOBadgeSettings class]
                                     rootClass:[POGOBadgeSettingsRoot class]
                                          file:POGOBadgeSettingsRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(POGOBadgeSettings__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t POGOBadgeSettings_BadgeType_RawValue(POGOBadgeSettings *message) {
  GPBDescriptor *descriptor = [POGOBadgeSettings descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGOBadgeSettings_FieldNumber_BadgeType];
  return GPBGetMessageInt32Field(message, field);
}

void SetPOGOBadgeSettings_BadgeType_RawValue(POGOBadgeSettings *message, int32_t value) {
  GPBDescriptor *descriptor = [POGOBadgeSettings descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGOBadgeSettings_FieldNumber_BadgeType];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
