// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Settings/Master/MoveSettings.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

GPB_ENUM_FWD_DECLARE(POGOPokemonMovementType);
GPB_ENUM_FWD_DECLARE(POGOPokemonType);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - POGOMoveSettingsRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface POGOMoveSettingsRoot : GPBRootObject
@end

#pragma mark - POGOMoveSettings

typedef GPB_ENUM(POGOMoveSettings_FieldNumber) {
  POGOMoveSettings_FieldNumber_MovementId = 1,
  POGOMoveSettings_FieldNumber_AnimationId = 2,
  POGOMoveSettings_FieldNumber_PokemonType = 3,
  POGOMoveSettings_FieldNumber_Power = 4,
  POGOMoveSettings_FieldNumber_AccuracyChance = 5,
  POGOMoveSettings_FieldNumber_CriticalChance = 6,
  POGOMoveSettings_FieldNumber_HealScalar = 7,
  POGOMoveSettings_FieldNumber_StaminaLossScalar = 8,
  POGOMoveSettings_FieldNumber_TrainerLevelMin = 9,
  POGOMoveSettings_FieldNumber_TrainerLevelMax = 10,
  POGOMoveSettings_FieldNumber_VfxName = 11,
  POGOMoveSettings_FieldNumber_DurationMs = 12,
  POGOMoveSettings_FieldNumber_DamageWindowStartMs = 13,
  POGOMoveSettings_FieldNumber_DamageWindowEndMs = 14,
  POGOMoveSettings_FieldNumber_EnergyDelta = 15,
};

@interface POGOMoveSettings : GPBMessage

@property(nonatomic, readwrite) enum POGOPokemonMovementType movementId;

@property(nonatomic, readwrite) int32_t animationId;

@property(nonatomic, readwrite) enum POGOPokemonType pokemonType;

@property(nonatomic, readwrite) float power;

@property(nonatomic, readwrite) float accuracyChance;

@property(nonatomic, readwrite) float criticalChance;

@property(nonatomic, readwrite) float healScalar;

@property(nonatomic, readwrite) float staminaLossScalar;

@property(nonatomic, readwrite) int32_t trainerLevelMin;

@property(nonatomic, readwrite) int32_t trainerLevelMax;

@property(nonatomic, readwrite, copy, null_resettable) NSString *vfxName;

@property(nonatomic, readwrite) int32_t durationMs;

@property(nonatomic, readwrite) int32_t damageWindowStartMs;

@property(nonatomic, readwrite) int32_t damageWindowEndMs;

@property(nonatomic, readwrite) int32_t energyDelta;

@end

/// Fetches the raw value of a @c POGOMoveSettings's @c movementId property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t POGOMoveSettings_MovementId_RawValue(POGOMoveSettings *message);
/// Sets the raw value of an @c POGOMoveSettings's @c movementId property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetPOGOMoveSettings_MovementId_RawValue(POGOMoveSettings *message, int32_t value);

/// Fetches the raw value of a @c POGOMoveSettings's @c pokemonType property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t POGOMoveSettings_PokemonType_RawValue(POGOMoveSettings *message);
/// Sets the raw value of an @c POGOMoveSettings's @c pokemonType property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetPOGOMoveSettings_PokemonType_RawValue(POGOMoveSettings *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
