// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pokemon.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Pokemon.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - PHProtoPokemonRoot

@implementation PHProtoPokemonRoot

@end

#pragma mark - PHProtoPokemonRoot_FileDescriptor

static GPBFileDescriptor *PHProtoPokemonRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto2];
  }
  return descriptor;
}

#pragma mark - PHProtoRequestEnvelop

@implementation PHProtoRequestEnvelop

@dynamic hasUnknown1, unknown1;
@dynamic hasRpcId, rpcId;
@dynamic requestsArray, requestsArray_Count;
@dynamic hasUnknown6, unknown6;
@dynamic hasLatitude, latitude;
@dynamic hasLongitude, longitude;
@dynamic hasAltitude, altitude;
@dynamic hasAuth, auth;
@dynamic hasUnknown11, unknown11;
@dynamic hasUnknown12, unknown12;

typedef struct PHProtoRequestEnvelop__storage_ {
  uint32_t _has_storage_[1];
  int32_t unknown1;
  NSMutableArray *requestsArray;
  PHProtoRequestEnvelop_Unknown6 *unknown6;
  PHProtoRequestEnvelop_AuthInfo *auth;
  PHProtoUnknownAuth *unknown11;
  int64_t rpcId;
  uint64_t latitude;
  uint64_t longitude;
  uint64_t altitude;
  int64_t unknown12;
} PHProtoRequestEnvelop__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "unknown1",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_FieldNumber_Unknown1,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop__storage_, unknown1),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "rpcId",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_FieldNumber_RpcId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop__storage_, rpcId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "requestsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PHProtoRequestEnvelop_Requests),
        .number = PHProtoRequestEnvelop_FieldNumber_RequestsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop__storage_, requestsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "unknown6",
        .dataTypeSpecific.className = GPBStringifySymbol(PHProtoRequestEnvelop_Unknown6),
        .number = PHProtoRequestEnvelop_FieldNumber_Unknown6,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop__storage_, unknown6),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "latitude",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_FieldNumber_Latitude,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop__storage_, latitude),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFixed64,
      },
      {
        .name = "longitude",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_FieldNumber_Longitude,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop__storage_, longitude),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFixed64,
      },
      {
        .name = "altitude",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_FieldNumber_Altitude,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop__storage_, altitude),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFixed64,
      },
      {
        .name = "auth",
        .dataTypeSpecific.className = GPBStringifySymbol(PHProtoRequestEnvelop_AuthInfo),
        .number = PHProtoRequestEnvelop_FieldNumber_Auth,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop__storage_, auth),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "unknown11",
        .dataTypeSpecific.className = GPBStringifySymbol(PHProtoUnknownAuth),
        .number = PHProtoRequestEnvelop_FieldNumber_Unknown11,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop__storage_, unknown11),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "unknown12",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_FieldNumber_Unknown12,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop__storage_, unknown12),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoRequestEnvelop class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoRequestEnvelop__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoRequestEnvelop_Requests

@implementation PHProtoRequestEnvelop_Requests

@dynamic hasType, type;
@dynamic hasMessage, message;

typedef struct PHProtoRequestEnvelop_Requests__storage_ {
  uint32_t _has_storage_[1];
  int32_t type;
  NSData *message;
} PHProtoRequestEnvelop_Requests__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "type",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_Requests_FieldNumber_Type,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop_Requests__storage_, type),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "message",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_Requests_FieldNumber_Message,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop_Requests__storage_, message),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoRequestEnvelop_Requests class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoRequestEnvelop_Requests__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoRequestEnvelop_MessageSingleString

@implementation PHProtoRequestEnvelop_MessageSingleString

@dynamic hasBytes, bytes;

typedef struct PHProtoRequestEnvelop_MessageSingleString__storage_ {
  uint32_t _has_storage_[1];
  NSData *bytes;
} PHProtoRequestEnvelop_MessageSingleString__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "bytes",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_MessageSingleString_FieldNumber_Bytes,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop_MessageSingleString__storage_, bytes),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoRequestEnvelop_MessageSingleString class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoRequestEnvelop_MessageSingleString__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoRequestEnvelop_MessageSingleInt

@implementation PHProtoRequestEnvelop_MessageSingleInt

@dynamic hasF1, f1;

typedef struct PHProtoRequestEnvelop_MessageSingleInt__storage_ {
  uint32_t _has_storage_[1];
  int64_t f1;
} PHProtoRequestEnvelop_MessageSingleInt__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "f1",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_MessageSingleInt_FieldNumber_F1,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop_MessageSingleInt__storage_, f1),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoRequestEnvelop_MessageSingleInt class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoRequestEnvelop_MessageSingleInt__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoRequestEnvelop_MessageTwoInts

@implementation PHProtoRequestEnvelop_MessageTwoInts

@dynamic hasF1, f1;
@dynamic hasF5, f5;

typedef struct PHProtoRequestEnvelop_MessageTwoInts__storage_ {
  uint32_t _has_storage_[1];
  int64_t f1;
  int64_t f5;
} PHProtoRequestEnvelop_MessageTwoInts__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "f1",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_MessageTwoInts_FieldNumber_F1,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop_MessageTwoInts__storage_, f1),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "f5",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_MessageTwoInts_FieldNumber_F5,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop_MessageTwoInts__storage_, f5),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoRequestEnvelop_MessageTwoInts class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoRequestEnvelop_MessageTwoInts__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoRequestEnvelop_MessageQuad

@implementation PHProtoRequestEnvelop_MessageQuad

@dynamic hasF1, f1;
@dynamic hasF2, f2;
@dynamic hasLat, lat;
@dynamic hasLong_p, long_p;

typedef struct PHProtoRequestEnvelop_MessageQuad__storage_ {
  uint32_t _has_storage_[1];
  NSData *f1;
  NSData *f2;
  uint64_t lat;
  uint64_t long_p;
} PHProtoRequestEnvelop_MessageQuad__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "f1",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_MessageQuad_FieldNumber_F1,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop_MessageQuad__storage_, f1),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "f2",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_MessageQuad_FieldNumber_F2,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop_MessageQuad__storage_, f2),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "lat",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_MessageQuad_FieldNumber_Lat,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop_MessageQuad__storage_, lat),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeFixed64,
      },
      {
        .name = "long_p",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_MessageQuad_FieldNumber_Long_p,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop_MessageQuad__storage_, long_p),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeFixed64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoRequestEnvelop_MessageQuad class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoRequestEnvelop_MessageQuad__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoRequestEnvelop_Wat

@implementation PHProtoRequestEnvelop_Wat

@dynamic lolsArray, lolsArray_Count;

typedef struct PHProtoRequestEnvelop_Wat__storage_ {
  uint32_t _has_storage_[1];
  GPBInt64Array *lolsArray;
} PHProtoRequestEnvelop_Wat__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "lolsArray",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_Wat_FieldNumber_LolsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop_Wat__storage_, lolsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoRequestEnvelop_Wat class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoRequestEnvelop_Wat__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoRequestEnvelop_Unknown3

@implementation PHProtoRequestEnvelop_Unknown3

@dynamic hasUnknown4, unknown4;
@dynamic hasUnknown2, unknown2;
@dynamic hasLat, lat;
@dynamic hasLong_p, long_p;

typedef struct PHProtoRequestEnvelop_Unknown3__storage_ {
  uint32_t _has_storage_[1];
  NSData *unknown4;
  NSData *unknown2;
  uint64_t lat;
  uint64_t long_p;
} PHProtoRequestEnvelop_Unknown3__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "unknown4",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_Unknown3_FieldNumber_Unknown4,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop_Unknown3__storage_, unknown4),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "unknown2",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_Unknown3_FieldNumber_Unknown2,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop_Unknown3__storage_, unknown2),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "lat",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_Unknown3_FieldNumber_Lat,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop_Unknown3__storage_, lat),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFixed64,
      },
      {
        .name = "long_p",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_Unknown3_FieldNumber_Long_p,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop_Unknown3__storage_, long_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeFixed64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoRequestEnvelop_Unknown3 class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoRequestEnvelop_Unknown3__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoRequestEnvelop_Unknown6

@implementation PHProtoRequestEnvelop_Unknown6

@dynamic hasUnknown1, unknown1;
@dynamic hasUnknown2, unknown2;

typedef struct PHProtoRequestEnvelop_Unknown6__storage_ {
  uint32_t _has_storage_[1];
  int32_t unknown1;
  PHProtoRequestEnvelop_Unknown6_Unknown2 *unknown2;
} PHProtoRequestEnvelop_Unknown6__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "unknown1",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_Unknown6_FieldNumber_Unknown1,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop_Unknown6__storage_, unknown1),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "unknown2",
        .dataTypeSpecific.className = GPBStringifySymbol(PHProtoRequestEnvelop_Unknown6_Unknown2),
        .number = PHProtoRequestEnvelop_Unknown6_FieldNumber_Unknown2,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop_Unknown6__storage_, unknown2),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoRequestEnvelop_Unknown6 class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoRequestEnvelop_Unknown6__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoRequestEnvelop_Unknown6_Unknown2

@implementation PHProtoRequestEnvelop_Unknown6_Unknown2

@dynamic hasUnknown1, unknown1;

typedef struct PHProtoRequestEnvelop_Unknown6_Unknown2__storage_ {
  uint32_t _has_storage_[1];
  NSData *unknown1;
} PHProtoRequestEnvelop_Unknown6_Unknown2__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "unknown1",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_Unknown6_Unknown2_FieldNumber_Unknown1,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop_Unknown6_Unknown2__storage_, unknown1),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoRequestEnvelop_Unknown6_Unknown2 class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoRequestEnvelop_Unknown6_Unknown2__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoRequestEnvelop_AuthInfo

@implementation PHProtoRequestEnvelop_AuthInfo

@dynamic hasProvider, provider;
@dynamic hasToken, token;

typedef struct PHProtoRequestEnvelop_AuthInfo__storage_ {
  uint32_t _has_storage_[1];
  NSString *provider;
  PHProtoRequestEnvelop_AuthInfo_JWT *token;
} PHProtoRequestEnvelop_AuthInfo__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "provider",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_AuthInfo_FieldNumber_Provider,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop_AuthInfo__storage_, provider),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "token",
        .dataTypeSpecific.className = GPBStringifySymbol(PHProtoRequestEnvelop_AuthInfo_JWT),
        .number = PHProtoRequestEnvelop_AuthInfo_FieldNumber_Token,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop_AuthInfo__storage_, token),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoRequestEnvelop_AuthInfo class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoRequestEnvelop_AuthInfo__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoRequestEnvelop_AuthInfo_JWT

@implementation PHProtoRequestEnvelop_AuthInfo_JWT

@dynamic hasContents, contents;
@dynamic hasUnknown13, unknown13;

typedef struct PHProtoRequestEnvelop_AuthInfo_JWT__storage_ {
  uint32_t _has_storage_[1];
  int32_t unknown13;
  NSString *contents;
} PHProtoRequestEnvelop_AuthInfo_JWT__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "contents",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_AuthInfo_JWT_FieldNumber_Contents,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop_AuthInfo_JWT__storage_, contents),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "unknown13",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoRequestEnvelop_AuthInfo_JWT_FieldNumber_Unknown13,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoRequestEnvelop_AuthInfo_JWT__storage_, unknown13),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoRequestEnvelop_AuthInfo_JWT class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoRequestEnvelop_AuthInfo_JWT__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoUnknownAuth

@implementation PHProtoUnknownAuth

@dynamic hasUnknown71, unknown71;
@dynamic hasUnknown72, unknown72;
@dynamic hasUnknown73, unknown73;

typedef struct PHProtoUnknownAuth__storage_ {
  uint32_t _has_storage_[1];
  NSData *unknown71;
  NSData *unknown73;
  int64_t unknown72;
} PHProtoUnknownAuth__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "unknown71",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoUnknownAuth_FieldNumber_Unknown71,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoUnknownAuth__storage_, unknown71),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "unknown72",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoUnknownAuth_FieldNumber_Unknown72,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoUnknownAuth__storage_, unknown72),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "unknown73",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoUnknownAuth_FieldNumber_Unknown73,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PHProtoUnknownAuth__storage_, unknown73),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoUnknownAuth class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoUnknownAuth__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoResponseEnvelop

@implementation PHProtoResponseEnvelop

@dynamic hasUnknown1, unknown1;
@dynamic hasUnknown2, unknown2;
@dynamic hasApiURL, apiURL;
@dynamic hasUnknown6, unknown6;
@dynamic hasUnknown7, unknown7;
@dynamic payloadArray, payloadArray_Count;

typedef struct PHProtoResponseEnvelop__storage_ {
  uint32_t _has_storage_[1];
  int32_t unknown1;
  NSString *apiURL;
  PHProtoResponseEnvelop_Unknown6 *unknown6;
  PHProtoUnknownAuth *unknown7;
  NSMutableArray *payloadArray;
  int64_t unknown2;
} PHProtoResponseEnvelop__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "unknown1",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_FieldNumber_Unknown1,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop__storage_, unknown1),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "unknown2",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_FieldNumber_Unknown2,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop__storage_, unknown2),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "apiURL",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_FieldNumber_ApiURL,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop__storage_, apiURL),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "unknown6",
        .dataTypeSpecific.className = GPBStringifySymbol(PHProtoResponseEnvelop_Unknown6),
        .number = PHProtoResponseEnvelop_FieldNumber_Unknown6,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop__storage_, unknown6),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "unknown7",
        .dataTypeSpecific.className = GPBStringifySymbol(PHProtoUnknownAuth),
        .number = PHProtoResponseEnvelop_FieldNumber_Unknown7,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop__storage_, unknown7),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "payloadArray",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_FieldNumber_PayloadArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop__storage_, payloadArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoResponseEnvelop class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoResponseEnvelop__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\003\003\241!!\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoResponseEnvelop_Unknown6

@implementation PHProtoResponseEnvelop_Unknown6

@dynamic hasUnknown1, unknown1;
@dynamic hasUnknown2, unknown2;

typedef struct PHProtoResponseEnvelop_Unknown6__storage_ {
  uint32_t _has_storage_[1];
  int32_t unknown1;
  PHProtoResponseEnvelop_Unknown6_Unknown2 *unknown2;
} PHProtoResponseEnvelop_Unknown6__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "unknown1",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_Unknown6_FieldNumber_Unknown1,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_Unknown6__storage_, unknown1),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "unknown2",
        .dataTypeSpecific.className = GPBStringifySymbol(PHProtoResponseEnvelop_Unknown6_Unknown2),
        .number = PHProtoResponseEnvelop_Unknown6_FieldNumber_Unknown2,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_Unknown6__storage_, unknown2),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoResponseEnvelop_Unknown6 class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoResponseEnvelop_Unknown6__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoResponseEnvelop_Unknown6_Unknown2

@implementation PHProtoResponseEnvelop_Unknown6_Unknown2

@dynamic hasUnknown1, unknown1;

typedef struct PHProtoResponseEnvelop_Unknown6_Unknown2__storage_ {
  uint32_t _has_storage_[1];
  NSData *unknown1;
} PHProtoResponseEnvelop_Unknown6_Unknown2__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "unknown1",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_Unknown6_Unknown2_FieldNumber_Unknown1,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_Unknown6_Unknown2__storage_, unknown1),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeBytes,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoResponseEnvelop_Unknown6_Unknown2 class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoResponseEnvelop_Unknown6_Unknown2__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoResponseEnvelop_HeartbeatPayload

@implementation PHProtoResponseEnvelop_HeartbeatPayload

@dynamic cellsArray, cellsArray_Count;

typedef struct PHProtoResponseEnvelop_HeartbeatPayload__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *cellsArray;
} PHProtoResponseEnvelop_HeartbeatPayload__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "cellsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PHProtoResponseEnvelop_ClientMapCell),
        .number = PHProtoResponseEnvelop_HeartbeatPayload_FieldNumber_CellsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_HeartbeatPayload__storage_, cellsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoResponseEnvelop_HeartbeatPayload class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoResponseEnvelop_HeartbeatPayload__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoResponseEnvelop_ClientMapCell

@implementation PHProtoResponseEnvelop_ClientMapCell

@dynamic hasS2CellId, s2CellId;
@dynamic hasAsOfTimeMs, asOfTimeMs;
@dynamic fortArray, fortArray_Count;
@dynamic spawnPointArray, spawnPointArray_Count;
@dynamic wildPokemonArray, wildPokemonArray_Count;
@dynamic hasIsTruncatedList, isTruncatedList;
@dynamic fortSummaryArray, fortSummaryArray_Count;
@dynamic decimatedSpawnPointArray, decimatedSpawnPointArray_Count;
@dynamic mapPokemonArray, mapPokemonArray_Count;
@dynamic nearbyPokemonArray, nearbyPokemonArray_Count;

typedef struct PHProtoResponseEnvelop_ClientMapCell__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *fortArray;
  NSMutableArray *spawnPointArray;
  NSMutableArray *wildPokemonArray;
  NSMutableArray *fortSummaryArray;
  NSMutableArray *decimatedSpawnPointArray;
  NSMutableArray *mapPokemonArray;
  NSMutableArray *nearbyPokemonArray;
  uint64_t s2CellId;
  int64_t asOfTimeMs;
} PHProtoResponseEnvelop_ClientMapCell__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "s2CellId",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_ClientMapCell_FieldNumber_S2CellId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_ClientMapCell__storage_, s2CellId),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeUInt64,
      },
      {
        .name = "asOfTimeMs",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_ClientMapCell_FieldNumber_AsOfTimeMs,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_ClientMapCell__storage_, asOfTimeMs),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "fortArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PHProtoResponseEnvelop_PokemonFortProto),
        .number = PHProtoResponseEnvelop_ClientMapCell_FieldNumber_FortArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_ClientMapCell__storage_, fortArray),
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "spawnPointArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PHProtoResponseEnvelop_ClientSpawnPointProto),
        .number = PHProtoResponseEnvelop_ClientMapCell_FieldNumber_SpawnPointArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_ClientMapCell__storage_, spawnPointArray),
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "wildPokemonArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PHProtoResponseEnvelop_WildPokemonProto),
        .number = PHProtoResponseEnvelop_ClientMapCell_FieldNumber_WildPokemonArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_ClientMapCell__storage_, wildPokemonArray),
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "isTruncatedList",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_ClientMapCell_FieldNumber_IsTruncatedList,
        .hasIndex = 2,
        .offset = 3,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "fortSummaryArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PHProtoResponseEnvelop_PokemonSummaryFortProto),
        .number = PHProtoResponseEnvelop_ClientMapCell_FieldNumber_FortSummaryArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_ClientMapCell__storage_, fortSummaryArray),
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "decimatedSpawnPointArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PHProtoResponseEnvelop_ClientSpawnPointProto),
        .number = PHProtoResponseEnvelop_ClientMapCell_FieldNumber_DecimatedSpawnPointArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_ClientMapCell__storage_, decimatedSpawnPointArray),
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "mapPokemonArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PHProtoResponseEnvelop_MapPokemonProto),
        .number = PHProtoResponseEnvelop_ClientMapCell_FieldNumber_MapPokemonArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_ClientMapCell__storage_, mapPokemonArray),
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "nearbyPokemonArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PHProtoResponseEnvelop_NearbyPokemonProto),
        .number = PHProtoResponseEnvelop_ClientMapCell_FieldNumber_NearbyPokemonArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_ClientMapCell__storage_, nearbyPokemonArray),
        .flags = GPBFieldRepeated | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoResponseEnvelop_ClientMapCell class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoResponseEnvelop_ClientMapCell__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\n\001H\000\002J\000\003\000Fort\000\004\000SpawnPoint\000\005\000WildPokemon"
        "\000\007O\000\010\000FortSummary\000\t\000DecimatedSpawnPoint\000"
        "\n\000MapPokemon\000\013\000NearbyPokemon\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoResponseEnvelop_WildPokemon

@implementation PHProtoResponseEnvelop_WildPokemon

@dynamic hasUniqueId, uniqueId;
@dynamic hasPokemonId, pokemonId;
@dynamic pokemonArray, pokemonArray_Count;

typedef struct PHProtoResponseEnvelop_WildPokemon__storage_ {
  uint32_t _has_storage_[1];
  NSString *uniqueId;
  NSString *pokemonId;
  NSMutableArray *pokemonArray;
} PHProtoResponseEnvelop_WildPokemon__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "uniqueId",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_WildPokemon_FieldNumber_UniqueId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_WildPokemon__storage_, uniqueId),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "pokemonId",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_WildPokemon_FieldNumber_PokemonId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_WildPokemon__storage_, pokemonId),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "pokemonArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PHProtoResponseEnvelop_NearbyPokemonProto),
        .number = PHProtoResponseEnvelop_WildPokemon_FieldNumber_PokemonArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_WildPokemon__storage_, pokemonArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoResponseEnvelop_WildPokemon class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoResponseEnvelop_WildPokemon__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001H\000\002I\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoResponseEnvelop_MapPokemonProto

@implementation PHProtoResponseEnvelop_MapPokemonProto

@dynamic hasSpawnpointId, spawnpointId;
@dynamic hasEncounterId, encounterId;
@dynamic hasPokedexTypeId, pokedexTypeId;
@dynamic hasExpirationTimeMs, expirationTimeMs;
@dynamic hasLatitude, latitude;
@dynamic hasLongitude, longitude;

typedef struct PHProtoResponseEnvelop_MapPokemonProto__storage_ {
  uint32_t _has_storage_[1];
  int32_t pokedexTypeId;
  NSString *spawnpointId;
  uint64_t encounterId;
  int64_t expirationTimeMs;
  double latitude;
  double longitude;
} PHProtoResponseEnvelop_MapPokemonProto__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "spawnpointId",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_MapPokemonProto_FieldNumber_SpawnpointId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_MapPokemonProto__storage_, spawnpointId),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "encounterId",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_MapPokemonProto_FieldNumber_EncounterId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_MapPokemonProto__storage_, encounterId),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeUInt64,
      },
      {
        .name = "pokedexTypeId",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_MapPokemonProto_FieldNumber_PokedexTypeId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_MapPokemonProto__storage_, pokedexTypeId),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "expirationTimeMs",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_MapPokemonProto_FieldNumber_ExpirationTimeMs,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_MapPokemonProto__storage_, expirationTimeMs),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "latitude",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_MapPokemonProto_FieldNumber_Latitude,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_MapPokemonProto__storage_, latitude),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "longitude",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_MapPokemonProto_FieldNumber_Longitude,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_MapPokemonProto__storage_, longitude),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeDouble,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoResponseEnvelop_MapPokemonProto class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoResponseEnvelop_MapPokemonProto__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\006\001L\000\002K\000\003M\000\004P\000\005H\000\006I\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoResponseEnvelop_PokemonFortProto

@implementation PHProtoResponseEnvelop_PokemonFortProto

@dynamic hasFortId, fortId;
@dynamic hasLastModifiedMs, lastModifiedMs;
@dynamic hasLatitude, latitude;
@dynamic hasLongitude, longitude;
@dynamic hasTeam, team;
@dynamic hasGuardPokemonId, guardPokemonId;
@dynamic hasGuardPokemonLevel, guardPokemonLevel;
@dynamic hasEnabled, enabled;
@dynamic hasFortType, fortType;
@dynamic hasGymPoints, gymPoints;
@dynamic hasIsInBattle, isInBattle;
@dynamic hasActivePortModifier, activePortModifier;
@dynamic hasLureInfo, lureInfo;
@dynamic hasCooldownCompleteMs, cooldownCompleteMs;
@dynamic hasSponsor, sponsor;
@dynamic hasRenderingType, renderingType;

typedef struct PHProtoResponseEnvelop_PokemonFortProto__storage_ {
  uint32_t _has_storage_[1];
  int32_t team;
  int32_t guardPokemonId;
  int32_t guardPokemonLevel;
  int32_t fortType;
  int32_t sponsor;
  int32_t renderingType;
  NSString *fortId;
  NSData *activePortModifier;
  PHProtoResponseEnvelop_FortLureInfoProto *lureInfo;
  int64_t lastModifiedMs;
  double latitude;
  double longitude;
  int64_t gymPoints;
  int64_t cooldownCompleteMs;
} PHProtoResponseEnvelop_PokemonFortProto__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "fortId",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_PokemonFortProto_FieldNumber_FortId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_PokemonFortProto__storage_, fortId),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "lastModifiedMs",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_PokemonFortProto_FieldNumber_LastModifiedMs,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_PokemonFortProto__storage_, lastModifiedMs),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "latitude",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_PokemonFortProto_FieldNumber_Latitude,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_PokemonFortProto__storage_, latitude),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "longitude",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_PokemonFortProto_FieldNumber_Longitude,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_PokemonFortProto__storage_, longitude),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "team",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_PokemonFortProto_FieldNumber_Team,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_PokemonFortProto__storage_, team),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "guardPokemonId",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_PokemonFortProto_FieldNumber_GuardPokemonId,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_PokemonFortProto__storage_, guardPokemonId),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "guardPokemonLevel",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_PokemonFortProto_FieldNumber_GuardPokemonLevel,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_PokemonFortProto__storage_, guardPokemonLevel),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "enabled",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_PokemonFortProto_FieldNumber_Enabled,
        .hasIndex = 7,
        .offset = 8,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "fortType",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_PokemonFortProto_FieldNumber_FortType,
        .hasIndex = 9,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_PokemonFortProto__storage_, fortType),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "gymPoints",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_PokemonFortProto_FieldNumber_GymPoints,
        .hasIndex = 10,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_PokemonFortProto__storage_, gymPoints),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "isInBattle",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_PokemonFortProto_FieldNumber_IsInBattle,
        .hasIndex = 11,
        .offset = 12,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "activePortModifier",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_PokemonFortProto_FieldNumber_ActivePortModifier,
        .hasIndex = 13,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_PokemonFortProto__storage_, activePortModifier),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "lureInfo",
        .dataTypeSpecific.className = GPBStringifySymbol(PHProtoResponseEnvelop_FortLureInfoProto),
        .number = PHProtoResponseEnvelop_PokemonFortProto_FieldNumber_LureInfo,
        .hasIndex = 14,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_PokemonFortProto__storage_, lureInfo),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "cooldownCompleteMs",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_PokemonFortProto_FieldNumber_CooldownCompleteMs,
        .hasIndex = 15,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_PokemonFortProto__storage_, cooldownCompleteMs),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "sponsor",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_PokemonFortProto_FieldNumber_Sponsor,
        .hasIndex = 16,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_PokemonFortProto__storage_, sponsor),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "renderingType",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_PokemonFortProto_FieldNumber_RenderingType,
        .hasIndex = 17,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_PokemonFortProto__storage_, renderingType),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoResponseEnvelop_PokemonFortProto class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoResponseEnvelop_PokemonFortProto__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\020\001F\000\002N\000\003H\000\004I\000\005D\000\006N\000\007Q\000\010G\000\tH\000\nI\000\013J\000\014R\000\rH\000"
        "\016R\000\017G\000\020M\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoResponseEnvelop_FortLureInfoProto

@implementation PHProtoResponseEnvelop_FortLureInfoProto

@dynamic hasFortId, fortId;
@dynamic hasUnknown2, unknown2;
@dynamic hasActivePokemonId, activePokemonId;
@dynamic hasLureExpiresTimestampMs, lureExpiresTimestampMs;
@dynamic hasDeployerPlayerCodename, deployerPlayerCodename;

typedef struct PHProtoResponseEnvelop_FortLureInfoProto__storage_ {
  uint32_t _has_storage_[1];
  int32_t activePokemonId;
  NSString *fortId;
  NSString *deployerPlayerCodename;
  double unknown2;
  int64_t lureExpiresTimestampMs;
} PHProtoResponseEnvelop_FortLureInfoProto__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "fortId",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_FortLureInfoProto_FieldNumber_FortId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_FortLureInfoProto__storage_, fortId),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "unknown2",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_FortLureInfoProto_FieldNumber_Unknown2,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_FortLureInfoProto__storage_, unknown2),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "activePokemonId",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_FortLureInfoProto_FieldNumber_ActivePokemonId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_FortLureInfoProto__storage_, activePokemonId),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "lureExpiresTimestampMs",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_FortLureInfoProto_FieldNumber_LureExpiresTimestampMs,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_FortLureInfoProto__storage_, lureExpiresTimestampMs),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "deployerPlayerCodename",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_FortLureInfoProto_FieldNumber_DeployerPlayerCodename,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_FortLureInfoProto__storage_, deployerPlayerCodename),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoResponseEnvelop_FortLureInfoProto class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoResponseEnvelop_FortLureInfoProto__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\004\001F\000\003O\000\004V\000\005V\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoResponseEnvelop_PokemonSummaryFortProto

@implementation PHProtoResponseEnvelop_PokemonSummaryFortProto

@dynamic hasFortSummaryId, fortSummaryId;
@dynamic hasLastModifiedMs, lastModifiedMs;
@dynamic hasLatitude, latitude;
@dynamic hasLongitude, longitude;

typedef struct PHProtoResponseEnvelop_PokemonSummaryFortProto__storage_ {
  uint32_t _has_storage_[1];
  NSString *fortSummaryId;
  int64_t lastModifiedMs;
  double latitude;
  double longitude;
} PHProtoResponseEnvelop_PokemonSummaryFortProto__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "fortSummaryId",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_PokemonSummaryFortProto_FieldNumber_FortSummaryId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_PokemonSummaryFortProto__storage_, fortSummaryId),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "lastModifiedMs",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_PokemonSummaryFortProto_FieldNumber_LastModifiedMs,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_PokemonSummaryFortProto__storage_, lastModifiedMs),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "latitude",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_PokemonSummaryFortProto_FieldNumber_Latitude,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_PokemonSummaryFortProto__storage_, latitude),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "longitude",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_PokemonSummaryFortProto_FieldNumber_Longitude,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_PokemonSummaryFortProto__storage_, longitude),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeDouble,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoResponseEnvelop_PokemonSummaryFortProto class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoResponseEnvelop_PokemonSummaryFortProto__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\004\001M\000\002N\000\003H\000\004I\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoResponseEnvelop_ClientSpawnPointProto

@implementation PHProtoResponseEnvelop_ClientSpawnPointProto

@dynamic hasLatitude, latitude;
@dynamic hasLongitude, longitude;

typedef struct PHProtoResponseEnvelop_ClientSpawnPointProto__storage_ {
  uint32_t _has_storage_[1];
  double latitude;
  double longitude;
} PHProtoResponseEnvelop_ClientSpawnPointProto__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "latitude",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_ClientSpawnPointProto_FieldNumber_Latitude,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_ClientSpawnPointProto__storage_, latitude),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "longitude",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_ClientSpawnPointProto_FieldNumber_Longitude,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_ClientSpawnPointProto__storage_, longitude),
        .flags = GPBFieldRequired | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeDouble,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoResponseEnvelop_ClientSpawnPointProto class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoResponseEnvelop_ClientSpawnPointProto__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\002H\000\003I\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoResponseEnvelop_WildPokemonProto

@implementation PHProtoResponseEnvelop_WildPokemonProto

@dynamic hasEncounterId, encounterId;
@dynamic hasLastModifiedMs, lastModifiedMs;
@dynamic hasLatitude, latitude;
@dynamic hasLongitude, longitude;
@dynamic hasSpawnPointId, spawnPointId;
@dynamic hasPokemon, pokemon;
@dynamic hasTimeTillHiddenMs, timeTillHiddenMs;

typedef struct PHProtoResponseEnvelop_WildPokemonProto__storage_ {
  uint32_t _has_storage_[1];
  int32_t timeTillHiddenMs;
  NSString *spawnPointId;
  PHProtoResponseEnvelop_WildPokemonProto_Pokemon *pokemon;
  uint64_t encounterId;
  int64_t lastModifiedMs;
  double latitude;
  double longitude;
} PHProtoResponseEnvelop_WildPokemonProto__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "encounterId",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_WildPokemonProto_FieldNumber_EncounterId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_WildPokemonProto__storage_, encounterId),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeUInt64,
      },
      {
        .name = "lastModifiedMs",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_WildPokemonProto_FieldNumber_LastModifiedMs,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_WildPokemonProto__storage_, lastModifiedMs),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "latitude",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_WildPokemonProto_FieldNumber_Latitude,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_WildPokemonProto__storage_, latitude),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "longitude",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_WildPokemonProto_FieldNumber_Longitude,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_WildPokemonProto__storage_, longitude),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "spawnPointId",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_WildPokemonProto_FieldNumber_SpawnPointId,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_WildPokemonProto__storage_, spawnPointId),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "pokemon",
        .dataTypeSpecific.className = GPBStringifySymbol(PHProtoResponseEnvelop_WildPokemonProto_Pokemon),
        .number = PHProtoResponseEnvelop_WildPokemonProto_FieldNumber_Pokemon,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_WildPokemonProto__storage_, pokemon),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "timeTillHiddenMs",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_WildPokemonProto_FieldNumber_TimeTillHiddenMs,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_WildPokemonProto__storage_, timeTillHiddenMs),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoResponseEnvelop_WildPokemonProto class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoResponseEnvelop_WildPokemonProto__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\006\001K\000\002N\000\003H\000\004I\000\005L\000\013P\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoResponseEnvelop_WildPokemonProto_Pokemon

@implementation PHProtoResponseEnvelop_WildPokemonProto_Pokemon

@dynamic hasId_p, id_p;
@dynamic hasPokemonId, pokemonId;

typedef struct PHProtoResponseEnvelop_WildPokemonProto_Pokemon__storage_ {
  uint32_t _has_storage_[1];
  int32_t pokemonId;
  uint64_t id_p;
} PHProtoResponseEnvelop_WildPokemonProto_Pokemon__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "id_p",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_WildPokemonProto_Pokemon_FieldNumber_Id_p,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_WildPokemonProto_Pokemon__storage_, id_p),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeUInt64,
      },
      {
        .name = "pokemonId",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_WildPokemonProto_Pokemon_FieldNumber_PokemonId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_WildPokemonProto_Pokemon__storage_, pokemonId),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoResponseEnvelop_WildPokemonProto_Pokemon class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoResponseEnvelop_WildPokemonProto_Pokemon__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001\000Id\000\002I\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoResponseEnvelop_NearbyPokemonProto

@implementation PHProtoResponseEnvelop_NearbyPokemonProto

@dynamic hasPokedexNumber, pokedexNumber;
@dynamic hasDistanceMeters, distanceMeters;
@dynamic hasEncounterId, encounterId;

typedef struct PHProtoResponseEnvelop_NearbyPokemonProto__storage_ {
  uint32_t _has_storage_[1];
  int32_t pokedexNumber;
  float distanceMeters;
  uint64_t encounterId;
} PHProtoResponseEnvelop_NearbyPokemonProto__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "pokedexNumber",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_NearbyPokemonProto_FieldNumber_PokedexNumber,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_NearbyPokemonProto__storage_, pokedexNumber),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "distanceMeters",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_NearbyPokemonProto_FieldNumber_DistanceMeters,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_NearbyPokemonProto__storage_, distanceMeters),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeFloat,
      },
      {
        .name = "encounterId",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_NearbyPokemonProto_FieldNumber_EncounterId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_NearbyPokemonProto__storage_, encounterId),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeUInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoResponseEnvelop_NearbyPokemonProto class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoResponseEnvelop_NearbyPokemonProto__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\003\001M\000\002N\000\003K\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoResponseEnvelop_ProfilePayload

@implementation PHProtoResponseEnvelop_ProfilePayload

@dynamic hasUnknown1, unknown1;
@dynamic hasProfile, profile;

typedef struct PHProtoResponseEnvelop_ProfilePayload__storage_ {
  uint32_t _has_storage_[1];
  int32_t unknown1;
  PHProtoResponseEnvelop_Profile *profile;
} PHProtoResponseEnvelop_ProfilePayload__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "unknown1",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_ProfilePayload_FieldNumber_Unknown1,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_ProfilePayload__storage_, unknown1),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "profile",
        .dataTypeSpecific.className = GPBStringifySymbol(PHProtoResponseEnvelop_Profile),
        .number = PHProtoResponseEnvelop_ProfilePayload_FieldNumber_Profile,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_ProfilePayload__storage_, profile),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoResponseEnvelop_ProfilePayload class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoResponseEnvelop_ProfilePayload__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoResponseEnvelop_Profile

@implementation PHProtoResponseEnvelop_Profile

@dynamic hasCreationTime, creationTime;
@dynamic hasUsername, username;
@dynamic hasTeam, team;
@dynamic hasTutorial, tutorial;
@dynamic hasAvatar, avatar;
@dynamic hasPokeStorage, pokeStorage;
@dynamic hasItemStorage, itemStorage;
@dynamic hasDailyBonus, dailyBonus;
@dynamic hasUnknown12, unknown12;
@dynamic hasUnknown13, unknown13;
@dynamic currencyArray, currencyArray_Count;

typedef struct PHProtoResponseEnvelop_Profile__storage_ {
  uint32_t _has_storage_[1];
  int32_t team;
  int32_t pokeStorage;
  int32_t itemStorage;
  NSString *username;
  NSData *tutorial;
  PHProtoResponseEnvelop_Profile_AvatarDetails *avatar;
  PHProtoResponseEnvelop_Profile_DailyBonus *dailyBonus;
  NSData *unknown12;
  NSData *unknown13;
  NSMutableArray *currencyArray;
  int64_t creationTime;
} PHProtoResponseEnvelop_Profile__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "creationTime",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_Profile_FieldNumber_CreationTime,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_Profile__storage_, creationTime),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "username",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_Profile_FieldNumber_Username,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_Profile__storage_, username),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "team",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_Profile_FieldNumber_Team,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_Profile__storage_, team),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "tutorial",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_Profile_FieldNumber_Tutorial,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_Profile__storage_, tutorial),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "avatar",
        .dataTypeSpecific.className = GPBStringifySymbol(PHProtoResponseEnvelop_Profile_AvatarDetails),
        .number = PHProtoResponseEnvelop_Profile_FieldNumber_Avatar,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_Profile__storage_, avatar),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "pokeStorage",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_Profile_FieldNumber_PokeStorage,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_Profile__storage_, pokeStorage),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "itemStorage",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_Profile_FieldNumber_ItemStorage,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_Profile__storage_, itemStorage),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "dailyBonus",
        .dataTypeSpecific.className = GPBStringifySymbol(PHProtoResponseEnvelop_Profile_DailyBonus),
        .number = PHProtoResponseEnvelop_Profile_FieldNumber_DailyBonus,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_Profile__storage_, dailyBonus),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "unknown12",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_Profile_FieldNumber_Unknown12,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_Profile__storage_, unknown12),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "unknown13",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_Profile_FieldNumber_Unknown13,
        .hasIndex = 9,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_Profile__storage_, unknown13),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "currencyArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PHProtoResponseEnvelop_Profile_Currency),
        .number = PHProtoResponseEnvelop_Profile_FieldNumber_CurrencyArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_Profile__storage_, currencyArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoResponseEnvelop_Profile class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoResponseEnvelop_Profile__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoResponseEnvelop_Profile_AvatarDetails

@implementation PHProtoResponseEnvelop_Profile_AvatarDetails

@dynamic hasUnknown2, unknown2;
@dynamic hasUnknown3, unknown3;
@dynamic hasUnknown9, unknown9;
@dynamic hasUnknown10, unknown10;

typedef struct PHProtoResponseEnvelop_Profile_AvatarDetails__storage_ {
  uint32_t _has_storage_[1];
  int32_t unknown2;
  int32_t unknown3;
  int32_t unknown9;
  int32_t unknown10;
} PHProtoResponseEnvelop_Profile_AvatarDetails__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "unknown2",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_Profile_AvatarDetails_FieldNumber_Unknown2,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_Profile_AvatarDetails__storage_, unknown2),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "unknown3",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_Profile_AvatarDetails_FieldNumber_Unknown3,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_Profile_AvatarDetails__storage_, unknown3),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "unknown9",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_Profile_AvatarDetails_FieldNumber_Unknown9,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_Profile_AvatarDetails__storage_, unknown9),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "unknown10",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_Profile_AvatarDetails_FieldNumber_Unknown10,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_Profile_AvatarDetails__storage_, unknown10),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoResponseEnvelop_Profile_AvatarDetails class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoResponseEnvelop_Profile_AvatarDetails__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoResponseEnvelop_Profile_DailyBonus

@implementation PHProtoResponseEnvelop_Profile_DailyBonus

@dynamic hasNextCollectTimestampMs, nextCollectTimestampMs;
@dynamic hasNextDefenderBonusCollectTimestampMs, nextDefenderBonusCollectTimestampMs;

typedef struct PHProtoResponseEnvelop_Profile_DailyBonus__storage_ {
  uint32_t _has_storage_[1];
  int64_t nextCollectTimestampMs;
  int64_t nextDefenderBonusCollectTimestampMs;
} PHProtoResponseEnvelop_Profile_DailyBonus__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "nextCollectTimestampMs",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_Profile_DailyBonus_FieldNumber_NextCollectTimestampMs,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_Profile_DailyBonus__storage_, nextCollectTimestampMs),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "nextDefenderBonusCollectTimestampMs",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_Profile_DailyBonus_FieldNumber_NextDefenderBonusCollectTimestampMs,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_Profile_DailyBonus__storage_, nextDefenderBonusCollectTimestampMs),
        .flags = GPBFieldOptional | GPBFieldTextFormatNameCustom,
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoResponseEnvelop_Profile_DailyBonus class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoResponseEnvelop_Profile_DailyBonus__storage_)
                                         flags:0];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001V\000\002_\004\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - PHProtoResponseEnvelop_Profile_Currency

@implementation PHProtoResponseEnvelop_Profile_Currency

@dynamic hasType, type;
@dynamic hasAmount, amount;

typedef struct PHProtoResponseEnvelop_Profile_Currency__storage_ {
  uint32_t _has_storage_[1];
  int32_t amount;
  NSString *type;
} PHProtoResponseEnvelop_Profile_Currency__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "type",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_Profile_Currency_FieldNumber_Type,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_Profile_Currency__storage_, type),
        .flags = GPBFieldRequired,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "amount",
        .dataTypeSpecific.className = NULL,
        .number = PHProtoResponseEnvelop_Profile_Currency_FieldNumber_Amount,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(PHProtoResponseEnvelop_Profile_Currency__storage_, amount),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[PHProtoResponseEnvelop_Profile_Currency class]
                                     rootClass:[PHProtoPokemonRoot class]
                                          file:PHProtoPokemonRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(PHProtoResponseEnvelop_Profile_Currency__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
