// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Enums/ItemCategory.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Enums/ItemCategory.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - POGOItemCategoryRoot

@implementation POGOItemCategoryRoot

@end

#pragma mark - Enum POGOItemCategory

GPBEnumDescriptor *POGOItemCategory_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "ItemCategoryNone\000ItemCategoryPokeball\000It"
        "emCategoryFood\000ItemCategoryMedicine\000Item"
        "CategoryBoost\000ItemCategoryUtilites\000ItemC"
        "ategoryCamera\000ItemCategoryDisk\000ItemCateg"
        "oryIncubator\000ItemCategoryIncense\000ItemCat"
        "egoryXpBoost\000ItemCategoryInventoryUpgrad"
        "e\000";
    static const int32_t values[] = {
        POGOItemCategory_ItemCategoryNone,
        POGOItemCategory_ItemCategoryPokeball,
        POGOItemCategory_ItemCategoryFood,
        POGOItemCategory_ItemCategoryMedicine,
        POGOItemCategory_ItemCategoryBoost,
        POGOItemCategory_ItemCategoryUtilites,
        POGOItemCategory_ItemCategoryCamera,
        POGOItemCategory_ItemCategoryDisk,
        POGOItemCategory_ItemCategoryIncubator,
        POGOItemCategory_ItemCategoryIncense,
        POGOItemCategory_ItemCategoryXpBoost,
        POGOItemCategory_ItemCategoryInventoryUpgrade,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(POGOItemCategory)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:POGOItemCategory_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL POGOItemCategory_IsValidValue(int32_t value__) {
  switch (value__) {
    case POGOItemCategory_ItemCategoryNone:
    case POGOItemCategory_ItemCategoryPokeball:
    case POGOItemCategory_ItemCategoryFood:
    case POGOItemCategory_ItemCategoryMedicine:
    case POGOItemCategory_ItemCategoryBoost:
    case POGOItemCategory_ItemCategoryUtilites:
    case POGOItemCategory_ItemCategoryCamera:
    case POGOItemCategory_ItemCategoryDisk:
    case POGOItemCategory_ItemCategoryIncubator:
    case POGOItemCategory_ItemCategoryIncense:
    case POGOItemCategory_ItemCategoryXpBoost:
    case POGOItemCategory_ItemCategoryInventoryUpgrade:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
