// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Enums/PokemonMove.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Enums/PokemonMove.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - POGOPokemonMoveRoot

@implementation POGOPokemonMoveRoot

@end

#pragma mark - Enum POGOPokemonMove

GPBEnumDescriptor *POGOPokemonMove_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "MoveUnset\000ThunderShock\000QuickAttack\000Scrat"
        "ch\000Ember\000VineWhip\000Tackle\000RazorLeaf\000TakeD"
        "own\000WaterGun\000Bite\000Pound\000DoubleSlap\000Wrap\000"
        "HyperBeam\000Lick\000DarkPulse\000Smog\000Sludge\000Met"
        "alClaw\000ViceGrip\000FlameWheel\000Megahorn\000Wing"
        "Attack\000Flamethrower\000SuckerPunch\000Dig\000LowK"
        "ick\000CrossChop\000PsychoCut\000Psybeam\000Earthqua"
        "ke\000StoneEdge\000IcePunch\000HeartStamp\000Dischar"
        "ge\000FlashCannon\000Peck\000DrillPeck\000IceBeam\000Bl"
        "izzard\000AirSlash\000HeatWave\000Twineedle\000Poiso"
        "nJab\000AerialAce\000DrillRun\000PetalBlizzard\000Me"
        "gaDrain\000BugBuzz\000PoisonFang\000NightSlash\000Sl"
        "ash\000BubbleBeam\000Submission\000KarateChop\000Low"
        "Sweep\000AquaJet\000AquaTail\000SeedBomb\000Psyshock"
        "\000RockThrow\000AncientPower\000RockTomb\000RockSli"
        "de\000PowerGem\000ShadowSneak\000ShadowPunch\000Shad"
        "owClaw\000OminousWind\000ShadowBall\000BulletPunc"
        "h\000MagnetBomb\000SteelWing\000IronHead\000Paraboli"
        "cCharge\000Spark\000ThunderPunch\000Thunder\000Thund"
        "erbolt\000Twister\000DragonBreath\000DragonPulse\000"
        "DragonClaw\000DisarmingVoice\000DrainingKiss\000D"
        "azzlingGleam\000Moonblast\000PlayRough\000CrossPo"
        "ison\000SludgeBomb\000SludgeWave\000GunkShot\000MudS"
        "hot\000BoneClub\000Bulldoze\000MudBomb\000FuryCutter"
        "\000BugBite\000SignalBeam\000XScissor\000FlameCharge"
        "\000FlameBurst\000FireBlast\000Brine\000WaterPulse\000S"
        "cald\000HydroPump\000Psychic\000Psystrike\000IceShar"
        "d\000IcyWind\000FrostBreath\000Absorb\000GigaDrain\000F"
        "irePunch\000SolarBeam\000LeafBlade\000PowerWhip\000S"
        "plash\000Acid\000AirCutter\000Hurricane\000BrickBrea"
        "k\000Cut\000Swift\000HornAttack\000Stomp\000Headbutt\000Hy"
        "perFang\000Slam\000BodySlam\000Rest\000Struggle\000Scal"
        "dBlastoise\000HydroPumpBlastoise\000WrapGreen\000"
        "WrapPink\000FuryCutterFast\000BugBiteFast\000Bite"
        "Fast\000SuckerPunchFast\000DragonBreathFast\000Th"
        "underShockFast\000SparkFast\000LowKickFast\000Kar"
        "ateChopFast\000EmberFast\000WingAttackFast\000Pec"
        "kFast\000LickFast\000ShadowClawFast\000VineWhipFa"
        "st\000RazorLeafFast\000MudShotFast\000IceShardFas"
        "t\000FrostBreathFast\000QuickAttackFast\000Scratc"
        "hFast\000TackleFast\000PoundFast\000CutFast\000Poiso"
        "nJabFast\000AcidFast\000PsychoCutFast\000RockThro"
        "wFast\000MetalClawFast\000BulletPunchFast\000Wate"
        "rGunFast\000SplashFast\000WaterGunFastBlastois"
        "e\000MudSlapFast\000ZenHeadbuttFast\000ConfusionF"
        "ast\000PoisonStingFast\000BubbleFast\000FeintAtta"
        "ckFast\000SteelWingFast\000FireFangFast\000RockSm"
        "ashFast\000";
    static const int32_t values[] = {
        POGOPokemonMove_MoveUnset,
        POGOPokemonMove_ThunderShock,
        POGOPokemonMove_QuickAttack,
        POGOPokemonMove_Scratch,
        POGOPokemonMove_Ember,
        POGOPokemonMove_VineWhip,
        POGOPokemonMove_Tackle,
        POGOPokemonMove_RazorLeaf,
        POGOPokemonMove_TakeDown,
        POGOPokemonMove_WaterGun,
        POGOPokemonMove_Bite,
        POGOPokemonMove_Pound,
        POGOPokemonMove_DoubleSlap,
        POGOPokemonMove_Wrap,
        POGOPokemonMove_HyperBeam,
        POGOPokemonMove_Lick,
        POGOPokemonMove_DarkPulse,
        POGOPokemonMove_Smog,
        POGOPokemonMove_Sludge,
        POGOPokemonMove_MetalClaw,
        POGOPokemonMove_ViceGrip,
        POGOPokemonMove_FlameWheel,
        POGOPokemonMove_Megahorn,
        POGOPokemonMove_WingAttack,
        POGOPokemonMove_Flamethrower,
        POGOPokemonMove_SuckerPunch,
        POGOPokemonMove_Dig,
        POGOPokemonMove_LowKick,
        POGOPokemonMove_CrossChop,
        POGOPokemonMove_PsychoCut,
        POGOPokemonMove_Psybeam,
        POGOPokemonMove_Earthquake,
        POGOPokemonMove_StoneEdge,
        POGOPokemonMove_IcePunch,
        POGOPokemonMove_HeartStamp,
        POGOPokemonMove_Discharge,
        POGOPokemonMove_FlashCannon,
        POGOPokemonMove_Peck,
        POGOPokemonMove_DrillPeck,
        POGOPokemonMove_IceBeam,
        POGOPokemonMove_Blizzard,
        POGOPokemonMove_AirSlash,
        POGOPokemonMove_HeatWave,
        POGOPokemonMove_Twineedle,
        POGOPokemonMove_PoisonJab,
        POGOPokemonMove_AerialAce,
        POGOPokemonMove_DrillRun,
        POGOPokemonMove_PetalBlizzard,
        POGOPokemonMove_MegaDrain,
        POGOPokemonMove_BugBuzz,
        POGOPokemonMove_PoisonFang,
        POGOPokemonMove_NightSlash,
        POGOPokemonMove_Slash,
        POGOPokemonMove_BubbleBeam,
        POGOPokemonMove_Submission,
        POGOPokemonMove_KarateChop,
        POGOPokemonMove_LowSweep,
        POGOPokemonMove_AquaJet,
        POGOPokemonMove_AquaTail,
        POGOPokemonMove_SeedBomb,
        POGOPokemonMove_Psyshock,
        POGOPokemonMove_RockThrow,
        POGOPokemonMove_AncientPower,
        POGOPokemonMove_RockTomb,
        POGOPokemonMove_RockSlide,
        POGOPokemonMove_PowerGem,
        POGOPokemonMove_ShadowSneak,
        POGOPokemonMove_ShadowPunch,
        POGOPokemonMove_ShadowClaw,
        POGOPokemonMove_OminousWind,
        POGOPokemonMove_ShadowBall,
        POGOPokemonMove_BulletPunch,
        POGOPokemonMove_MagnetBomb,
        POGOPokemonMove_SteelWing,
        POGOPokemonMove_IronHead,
        POGOPokemonMove_ParabolicCharge,
        POGOPokemonMove_Spark,
        POGOPokemonMove_ThunderPunch,
        POGOPokemonMove_Thunder,
        POGOPokemonMove_Thunderbolt,
        POGOPokemonMove_Twister,
        POGOPokemonMove_DragonBreath,
        POGOPokemonMove_DragonPulse,
        POGOPokemonMove_DragonClaw,
        POGOPokemonMove_DisarmingVoice,
        POGOPokemonMove_DrainingKiss,
        POGOPokemonMove_DazzlingGleam,
        POGOPokemonMove_Moonblast,
        POGOPokemonMove_PlayRough,
        POGOPokemonMove_CrossPoison,
        POGOPokemonMove_SludgeBomb,
        POGOPokemonMove_SludgeWave,
        POGOPokemonMove_GunkShot,
        POGOPokemonMove_MudShot,
        POGOPokemonMove_BoneClub,
        POGOPokemonMove_Bulldoze,
        POGOPokemonMove_MudBomb,
        POGOPokemonMove_FuryCutter,
        POGOPokemonMove_BugBite,
        POGOPokemonMove_SignalBeam,
        POGOPokemonMove_XScissor,
        POGOPokemonMove_FlameCharge,
        POGOPokemonMove_FlameBurst,
        POGOPokemonMove_FireBlast,
        POGOPokemonMove_Brine,
        POGOPokemonMove_WaterPulse,
        POGOPokemonMove_Scald,
        POGOPokemonMove_HydroPump,
        POGOPokemonMove_Psychic,
        POGOPokemonMove_Psystrike,
        POGOPokemonMove_IceShard,
        POGOPokemonMove_IcyWind,
        POGOPokemonMove_FrostBreath,
        POGOPokemonMove_Absorb,
        POGOPokemonMove_GigaDrain,
        POGOPokemonMove_FirePunch,
        POGOPokemonMove_SolarBeam,
        POGOPokemonMove_LeafBlade,
        POGOPokemonMove_PowerWhip,
        POGOPokemonMove_Splash,
        POGOPokemonMove_Acid,
        POGOPokemonMove_AirCutter,
        POGOPokemonMove_Hurricane,
        POGOPokemonMove_BrickBreak,
        POGOPokemonMove_Cut,
        POGOPokemonMove_Swift,
        POGOPokemonMove_HornAttack,
        POGOPokemonMove_Stomp,
        POGOPokemonMove_Headbutt,
        POGOPokemonMove_HyperFang,
        POGOPokemonMove_Slam,
        POGOPokemonMove_BodySlam,
        POGOPokemonMove_Rest,
        POGOPokemonMove_Struggle,
        POGOPokemonMove_ScaldBlastoise,
        POGOPokemonMove_HydroPumpBlastoise,
        POGOPokemonMove_WrapGreen,
        POGOPokemonMove_WrapPink,
        POGOPokemonMove_FuryCutterFast,
        POGOPokemonMove_BugBiteFast,
        POGOPokemonMove_BiteFast,
        POGOPokemonMove_SuckerPunchFast,
        POGOPokemonMove_DragonBreathFast,
        POGOPokemonMove_ThunderShockFast,
        POGOPokemonMove_SparkFast,
        POGOPokemonMove_LowKickFast,
        POGOPokemonMove_KarateChopFast,
        POGOPokemonMove_EmberFast,
        POGOPokemonMove_WingAttackFast,
        POGOPokemonMove_PeckFast,
        POGOPokemonMove_LickFast,
        POGOPokemonMove_ShadowClawFast,
        POGOPokemonMove_VineWhipFast,
        POGOPokemonMove_RazorLeafFast,
        POGOPokemonMove_MudShotFast,
        POGOPokemonMove_IceShardFast,
        POGOPokemonMove_FrostBreathFast,
        POGOPokemonMove_QuickAttackFast,
        POGOPokemonMove_ScratchFast,
        POGOPokemonMove_TackleFast,
        POGOPokemonMove_PoundFast,
        POGOPokemonMove_CutFast,
        POGOPokemonMove_PoisonJabFast,
        POGOPokemonMove_AcidFast,
        POGOPokemonMove_PsychoCutFast,
        POGOPokemonMove_RockThrowFast,
        POGOPokemonMove_MetalClawFast,
        POGOPokemonMove_BulletPunchFast,
        POGOPokemonMove_WaterGunFast,
        POGOPokemonMove_SplashFast,
        POGOPokemonMove_WaterGunFastBlastoise,
        POGOPokemonMove_MudSlapFast,
        POGOPokemonMove_ZenHeadbuttFast,
        POGOPokemonMove_ConfusionFast,
        POGOPokemonMove_PoisonStingFast,
        POGOPokemonMove_BubbleFast,
        POGOPokemonMove_FeintAttackFast,
        POGOPokemonMove_SteelWingFast,
        POGOPokemonMove_FireFangFast,
        POGOPokemonMove_RockSmashFast,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(POGOPokemonMove)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:POGOPokemonMove_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL POGOPokemonMove_IsValidValue(int32_t value__) {
  switch (value__) {
    case POGOPokemonMove_MoveUnset:
    case POGOPokemonMove_ThunderShock:
    case POGOPokemonMove_QuickAttack:
    case POGOPokemonMove_Scratch:
    case POGOPokemonMove_Ember:
    case POGOPokemonMove_VineWhip:
    case POGOPokemonMove_Tackle:
    case POGOPokemonMove_RazorLeaf:
    case POGOPokemonMove_TakeDown:
    case POGOPokemonMove_WaterGun:
    case POGOPokemonMove_Bite:
    case POGOPokemonMove_Pound:
    case POGOPokemonMove_DoubleSlap:
    case POGOPokemonMove_Wrap:
    case POGOPokemonMove_HyperBeam:
    case POGOPokemonMove_Lick:
    case POGOPokemonMove_DarkPulse:
    case POGOPokemonMove_Smog:
    case POGOPokemonMove_Sludge:
    case POGOPokemonMove_MetalClaw:
    case POGOPokemonMove_ViceGrip:
    case POGOPokemonMove_FlameWheel:
    case POGOPokemonMove_Megahorn:
    case POGOPokemonMove_WingAttack:
    case POGOPokemonMove_Flamethrower:
    case POGOPokemonMove_SuckerPunch:
    case POGOPokemonMove_Dig:
    case POGOPokemonMove_LowKick:
    case POGOPokemonMove_CrossChop:
    case POGOPokemonMove_PsychoCut:
    case POGOPokemonMove_Psybeam:
    case POGOPokemonMove_Earthquake:
    case POGOPokemonMove_StoneEdge:
    case POGOPokemonMove_IcePunch:
    case POGOPokemonMove_HeartStamp:
    case POGOPokemonMove_Discharge:
    case POGOPokemonMove_FlashCannon:
    case POGOPokemonMove_Peck:
    case POGOPokemonMove_DrillPeck:
    case POGOPokemonMove_IceBeam:
    case POGOPokemonMove_Blizzard:
    case POGOPokemonMove_AirSlash:
    case POGOPokemonMove_HeatWave:
    case POGOPokemonMove_Twineedle:
    case POGOPokemonMove_PoisonJab:
    case POGOPokemonMove_AerialAce:
    case POGOPokemonMove_DrillRun:
    case POGOPokemonMove_PetalBlizzard:
    case POGOPokemonMove_MegaDrain:
    case POGOPokemonMove_BugBuzz:
    case POGOPokemonMove_PoisonFang:
    case POGOPokemonMove_NightSlash:
    case POGOPokemonMove_Slash:
    case POGOPokemonMove_BubbleBeam:
    case POGOPokemonMove_Submission:
    case POGOPokemonMove_KarateChop:
    case POGOPokemonMove_LowSweep:
    case POGOPokemonMove_AquaJet:
    case POGOPokemonMove_AquaTail:
    case POGOPokemonMove_SeedBomb:
    case POGOPokemonMove_Psyshock:
    case POGOPokemonMove_RockThrow:
    case POGOPokemonMove_AncientPower:
    case POGOPokemonMove_RockTomb:
    case POGOPokemonMove_RockSlide:
    case POGOPokemonMove_PowerGem:
    case POGOPokemonMove_ShadowSneak:
    case POGOPokemonMove_ShadowPunch:
    case POGOPokemonMove_ShadowClaw:
    case POGOPokemonMove_OminousWind:
    case POGOPokemonMove_ShadowBall:
    case POGOPokemonMove_BulletPunch:
    case POGOPokemonMove_MagnetBomb:
    case POGOPokemonMove_SteelWing:
    case POGOPokemonMove_IronHead:
    case POGOPokemonMove_ParabolicCharge:
    case POGOPokemonMove_Spark:
    case POGOPokemonMove_ThunderPunch:
    case POGOPokemonMove_Thunder:
    case POGOPokemonMove_Thunderbolt:
    case POGOPokemonMove_Twister:
    case POGOPokemonMove_DragonBreath:
    case POGOPokemonMove_DragonPulse:
    case POGOPokemonMove_DragonClaw:
    case POGOPokemonMove_DisarmingVoice:
    case POGOPokemonMove_DrainingKiss:
    case POGOPokemonMove_DazzlingGleam:
    case POGOPokemonMove_Moonblast:
    case POGOPokemonMove_PlayRough:
    case POGOPokemonMove_CrossPoison:
    case POGOPokemonMove_SludgeBomb:
    case POGOPokemonMove_SludgeWave:
    case POGOPokemonMove_GunkShot:
    case POGOPokemonMove_MudShot:
    case POGOPokemonMove_BoneClub:
    case POGOPokemonMove_Bulldoze:
    case POGOPokemonMove_MudBomb:
    case POGOPokemonMove_FuryCutter:
    case POGOPokemonMove_BugBite:
    case POGOPokemonMove_SignalBeam:
    case POGOPokemonMove_XScissor:
    case POGOPokemonMove_FlameCharge:
    case POGOPokemonMove_FlameBurst:
    case POGOPokemonMove_FireBlast:
    case POGOPokemonMove_Brine:
    case POGOPokemonMove_WaterPulse:
    case POGOPokemonMove_Scald:
    case POGOPokemonMove_HydroPump:
    case POGOPokemonMove_Psychic:
    case POGOPokemonMove_Psystrike:
    case POGOPokemonMove_IceShard:
    case POGOPokemonMove_IcyWind:
    case POGOPokemonMove_FrostBreath:
    case POGOPokemonMove_Absorb:
    case POGOPokemonMove_GigaDrain:
    case POGOPokemonMove_FirePunch:
    case POGOPokemonMove_SolarBeam:
    case POGOPokemonMove_LeafBlade:
    case POGOPokemonMove_PowerWhip:
    case POGOPokemonMove_Splash:
    case POGOPokemonMove_Acid:
    case POGOPokemonMove_AirCutter:
    case POGOPokemonMove_Hurricane:
    case POGOPokemonMove_BrickBreak:
    case POGOPokemonMove_Cut:
    case POGOPokemonMove_Swift:
    case POGOPokemonMove_HornAttack:
    case POGOPokemonMove_Stomp:
    case POGOPokemonMove_Headbutt:
    case POGOPokemonMove_HyperFang:
    case POGOPokemonMove_Slam:
    case POGOPokemonMove_BodySlam:
    case POGOPokemonMove_Rest:
    case POGOPokemonMove_Struggle:
    case POGOPokemonMove_ScaldBlastoise:
    case POGOPokemonMove_HydroPumpBlastoise:
    case POGOPokemonMove_WrapGreen:
    case POGOPokemonMove_WrapPink:
    case POGOPokemonMove_FuryCutterFast:
    case POGOPokemonMove_BugBiteFast:
    case POGOPokemonMove_BiteFast:
    case POGOPokemonMove_SuckerPunchFast:
    case POGOPokemonMove_DragonBreathFast:
    case POGOPokemonMove_ThunderShockFast:
    case POGOPokemonMove_SparkFast:
    case POGOPokemonMove_LowKickFast:
    case POGOPokemonMove_KarateChopFast:
    case POGOPokemonMove_EmberFast:
    case POGOPokemonMove_WingAttackFast:
    case POGOPokemonMove_PeckFast:
    case POGOPokemonMove_LickFast:
    case POGOPokemonMove_ShadowClawFast:
    case POGOPokemonMove_VineWhipFast:
    case POGOPokemonMove_RazorLeafFast:
    case POGOPokemonMove_MudShotFast:
    case POGOPokemonMove_IceShardFast:
    case POGOPokemonMove_FrostBreathFast:
    case POGOPokemonMove_QuickAttackFast:
    case POGOPokemonMove_ScratchFast:
    case POGOPokemonMove_TackleFast:
    case POGOPokemonMove_PoundFast:
    case POGOPokemonMove_CutFast:
    case POGOPokemonMove_PoisonJabFast:
    case POGOPokemonMove_AcidFast:
    case POGOPokemonMove_PsychoCutFast:
    case POGOPokemonMove_RockThrowFast:
    case POGOPokemonMove_MetalClawFast:
    case POGOPokemonMove_BulletPunchFast:
    case POGOPokemonMove_WaterGunFast:
    case POGOPokemonMove_SplashFast:
    case POGOPokemonMove_WaterGunFastBlastoise:
    case POGOPokemonMove_MudSlapFast:
    case POGOPokemonMove_ZenHeadbuttFast:
    case POGOPokemonMove_ConfusionFast:
    case POGOPokemonMove_PoisonStingFast:
    case POGOPokemonMove_BubbleFast:
    case POGOPokemonMove_FeintAttackFast:
    case POGOPokemonMove_SteelWingFast:
    case POGOPokemonMove_FireFangFast:
    case POGOPokemonMove_RockSmashFast:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
