// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Enums/TeamColor.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Enums/TeamColor.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - POGOTeamColorRoot

@implementation POGOTeamColorRoot

@end

#pragma mark - Enum POGOTeamColor

GPBEnumDescriptor *POGOTeamColor_EnumDescriptor(void) {
  static GPBEnumDescriptor *descriptor = NULL;
  if (!descriptor) {
    static const char *valueNames =
        "Neutral\000Blue\000Red\000Yellow\000";
    static const int32_t values[] = {
        POGOTeamColor_Neutral,
        POGOTeamColor_Blue,
        POGOTeamColor_Red,
        POGOTeamColor_Yellow,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(POGOTeamColor)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:POGOTeamColor_IsValidValue];
    if (!OSAtomicCompareAndSwapPtrBarrier(nil, worker, (void * volatile *)&descriptor)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL POGOTeamColor_IsValidValue(int32_t value__) {
  switch (value__) {
    case POGOTeamColor_Neutral:
    case POGOTeamColor_Blue:
    case POGOTeamColor_Red:
    case POGOTeamColor_Yellow:
      return YES;
    default:
      return NO;
  }
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
