// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Map/Fort/FortModifier.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Map/Fort/FortModifier.pbobjc.h"
 #import "POGOProtos/Inventory/Item/ItemId.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - POGOFortModifierRoot

@implementation POGOFortModifierRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[POGOItemIdRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - POGOFortModifierRoot_FileDescriptor

static GPBFileDescriptor *POGOFortModifierRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Map.Fort"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - POGOFortModifier

@implementation POGOFortModifier

@dynamic itemId;
@dynamic expirationTimestampMs;
@dynamic deployerPlayerCodename;

typedef struct POGOFortModifier__storage_ {
  uint32_t _has_storage_[1];
  POGOItemId itemId;
  NSString *deployerPlayerCodename;
  int64_t expirationTimestampMs;
} POGOFortModifier__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "itemId",
        .dataTypeSpecific.enumDescFunc = POGOItemId_EnumDescriptor,
        .number = POGOFortModifier_FieldNumber_ItemId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(POGOFortModifier__storage_, itemId),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "expirationTimestampMs",
        .dataTypeSpecific.className = NULL,
        .number = POGOFortModifier_FieldNumber_ExpirationTimestampMs,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(POGOFortModifier__storage_, expirationTimestampMs),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "deployerPlayerCodename",
        .dataTypeSpecific.className = NULL,
        .number = POGOFortModifier_FieldNumber_DeployerPlayerCodename,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(POGOFortModifier__storage_, deployerPlayerCodename),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[POGOFortModifier class]
                                     rootClass:[POGOFortModifierRoot class]
                                          file:POGOFortModifierRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(POGOFortModifier__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t POGOFortModifier_ItemId_RawValue(POGOFortModifier *message) {
  GPBDescriptor *descriptor = [POGOFortModifier descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGOFortModifier_FieldNumber_ItemId];
  return GPBGetMessageInt32Field(message, field);
}

void SetPOGOFortModifier_ItemId_RawValue(POGOFortModifier *message, int32_t value) {
  GPBDescriptor *descriptor = [POGOFortModifier descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGOFortModifier_FieldNumber_ItemId];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
