// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Requests/Messages/AddFortModifierMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Networking/Requests/Messages/AddFortModifierMessage.pbobjc.h"
 #import "POGOProtos/Inventory/Item/ItemId.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - POGOAddFortModifierMessageRoot

@implementation POGOAddFortModifierMessageRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[POGOItemIdRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - POGOAddFortModifierMessageRoot_FileDescriptor

static GPBFileDescriptor *POGOAddFortModifierMessageRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Networking.Requests.Messages"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - POGOAddFortModifierMessage

@implementation POGOAddFortModifierMessage

@dynamic modifierType;
@dynamic fortId;
@dynamic playerLatitude;
@dynamic playerLongitude;

typedef struct POGOAddFortModifierMessage__storage_ {
  uint32_t _has_storage_[1];
  POGOItemId modifierType;
  NSString *fortId;
  double playerLatitude;
  double playerLongitude;
} POGOAddFortModifierMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "modifierType",
        .dataTypeSpecific.enumDescFunc = POGOItemId_EnumDescriptor,
        .number = POGOAddFortModifierMessage_FieldNumber_ModifierType,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(POGOAddFortModifierMessage__storage_, modifierType),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "fortId",
        .dataTypeSpecific.className = NULL,
        .number = POGOAddFortModifierMessage_FieldNumber_FortId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(POGOAddFortModifierMessage__storage_, fortId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "playerLatitude",
        .dataTypeSpecific.className = NULL,
        .number = POGOAddFortModifierMessage_FieldNumber_PlayerLatitude,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(POGOAddFortModifierMessage__storage_, playerLatitude),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "playerLongitude",
        .dataTypeSpecific.className = NULL,
        .number = POGOAddFortModifierMessage_FieldNumber_PlayerLongitude,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(POGOAddFortModifierMessage__storage_, playerLongitude),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[POGOAddFortModifierMessage class]
                                     rootClass:[POGOAddFortModifierMessageRoot class]
                                          file:POGOAddFortModifierMessageRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(POGOAddFortModifierMessage__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t POGOAddFortModifierMessage_ModifierType_RawValue(POGOAddFortModifierMessage *message) {
  GPBDescriptor *descriptor = [POGOAddFortModifierMessage descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGOAddFortModifierMessage_FieldNumber_ModifierType];
  return GPBGetMessageInt32Field(message, field);
}

void SetPOGOAddFortModifierMessage_ModifierType_RawValue(POGOAddFortModifierMessage *message, int32_t value) {
  GPBDescriptor *descriptor = [POGOAddFortModifierMessage descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGOAddFortModifierMessage_FieldNumber_ModifierType];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
