// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Requests/Messages/DownloadRemoteConfigVersionMessage.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Networking/Requests/Messages/DownloadRemoteConfigVersionMessage.pbobjc.h"
 #import "POGOProtos/Enums/Platform.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - POGODownloadRemoteConfigVersionMessageRoot

@implementation POGODownloadRemoteConfigVersionMessageRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[POGOPlatformRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - POGODownloadRemoteConfigVersionMessageRoot_FileDescriptor

static GPBFileDescriptor *POGODownloadRemoteConfigVersionMessageRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Networking.Requests.Messages"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - POGODownloadRemoteConfigVersionMessage

@implementation POGODownloadRemoteConfigVersionMessage

@dynamic platform;
@dynamic deviceManufacturer;
@dynamic deviceModel;
@dynamic locale;
@dynamic appVersion;

typedef struct POGODownloadRemoteConfigVersionMessage__storage_ {
  uint32_t _has_storage_[1];
  POGOPlatform platform;
  uint32_t appVersion;
  NSString *deviceManufacturer;
  NSString *deviceModel;
  NSString *locale;
} POGODownloadRemoteConfigVersionMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "platform",
        .dataTypeSpecific.enumDescFunc = POGOPlatform_EnumDescriptor,
        .number = POGODownloadRemoteConfigVersionMessage_FieldNumber_Platform,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(POGODownloadRemoteConfigVersionMessage__storage_, platform),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "deviceManufacturer",
        .dataTypeSpecific.className = NULL,
        .number = POGODownloadRemoteConfigVersionMessage_FieldNumber_DeviceManufacturer,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(POGODownloadRemoteConfigVersionMessage__storage_, deviceManufacturer),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceModel",
        .dataTypeSpecific.className = NULL,
        .number = POGODownloadRemoteConfigVersionMessage_FieldNumber_DeviceModel,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(POGODownloadRemoteConfigVersionMessage__storage_, deviceModel),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "locale",
        .dataTypeSpecific.className = NULL,
        .number = POGODownloadRemoteConfigVersionMessage_FieldNumber_Locale,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(POGODownloadRemoteConfigVersionMessage__storage_, locale),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "appVersion",
        .dataTypeSpecific.className = NULL,
        .number = POGODownloadRemoteConfigVersionMessage_FieldNumber_AppVersion,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(POGODownloadRemoteConfigVersionMessage__storage_, appVersion),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[POGODownloadRemoteConfigVersionMessage class]
                                     rootClass:[POGODownloadRemoteConfigVersionMessageRoot class]
                                          file:POGODownloadRemoteConfigVersionMessageRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(POGODownloadRemoteConfigVersionMessage__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t POGODownloadRemoteConfigVersionMessage_Platform_RawValue(POGODownloadRemoteConfigVersionMessage *message) {
  GPBDescriptor *descriptor = [POGODownloadRemoteConfigVersionMessage descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGODownloadRemoteConfigVersionMessage_FieldNumber_Platform];
  return GPBGetMessageInt32Field(message, field);
}

void SetPOGODownloadRemoteConfigVersionMessage_Platform_RawValue(POGODownloadRemoteConfigVersionMessage *message, int32_t value) {
  GPBDescriptor *descriptor = [POGODownloadRemoteConfigVersionMessage descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGODownloadRemoteConfigVersionMessage_FieldNumber_Platform];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
