// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Data/PokedexEntry.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

GPB_ENUM_FWD_DECLARE(POGOPokemonId);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - POGOPokedexEntryRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface POGOPokedexEntryRoot : GPBRootObject
@end

#pragma mark - POGOPokedexEntry

typedef GPB_ENUM(POGOPokedexEntry_FieldNumber) {
  POGOPokedexEntry_FieldNumber_PokemonId = 1,
  POGOPokedexEntry_FieldNumber_TimesEncountered = 2,
  POGOPokedexEntry_FieldNumber_TimesCaptured = 3,
  POGOPokedexEntry_FieldNumber_EvolutionStonePieces = 4,
  POGOPokedexEntry_FieldNumber_EvolutionStones = 5,
};

@interface POGOPokedexEntry : GPBMessage

@property(nonatomic, readwrite) enum POGOPokemonId pokemonId;

@property(nonatomic, readwrite) int32_t timesEncountered;

@property(nonatomic, readwrite) int32_t timesCaptured;

@property(nonatomic, readwrite) int32_t evolutionStonePieces;

@property(nonatomic, readwrite) int32_t evolutionStones;

@end

/// Fetches the raw value of a @c POGOPokedexEntry's @c pokemonId property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t POGOPokedexEntry_PokemonId_RawValue(POGOPokedexEntry *message);
/// Sets the raw value of an @c POGOPokedexEntry's @c pokemonId property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetPOGOPokedexEntry_PokemonId_RawValue(POGOPokedexEntry *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
