// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Inventory/EggIncubator.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/Inventory/EggIncubator.pbobjc.h"
 #import "POGOProtos/Inventory/Item/ItemId.pbobjc.h"
 #import "POGOProtos/Inventory/EggIncubatorType.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - POGOEggIncubatorRoot

@implementation POGOEggIncubatorRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[POGOItemIdRoot extensionRegistry]];
    [registry addExtensions:[POGOEggIncubatorTypeRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - POGOEggIncubatorRoot_FileDescriptor

static GPBFileDescriptor *POGOEggIncubatorRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.Inventory"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - POGOEggIncubator

@implementation POGOEggIncubator

@dynamic id_p;
@dynamic itemId;
@dynamic incubatorType;
@dynamic usesRemaining;
@dynamic pokemonId;
@dynamic startKmWalked;
@dynamic targetKmWalked;

typedef struct POGOEggIncubator__storage_ {
  uint32_t _has_storage_[1];
  POGOItemId itemId;
  POGOEggIncubatorType incubatorType;
  int32_t usesRemaining;
  NSString *id_p;
  uint64_t pokemonId;
  double startKmWalked;
  double targetKmWalked;
} POGOEggIncubator__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "id_p",
        .dataTypeSpecific.className = NULL,
        .number = POGOEggIncubator_FieldNumber_Id_p,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(POGOEggIncubator__storage_, id_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "itemId",
        .dataTypeSpecific.enumDescFunc = POGOItemId_EnumDescriptor,
        .number = POGOEggIncubator_FieldNumber_ItemId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(POGOEggIncubator__storage_, itemId),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "incubatorType",
        .dataTypeSpecific.enumDescFunc = POGOEggIncubatorType_EnumDescriptor,
        .number = POGOEggIncubator_FieldNumber_IncubatorType,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(POGOEggIncubator__storage_, incubatorType),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "usesRemaining",
        .dataTypeSpecific.className = NULL,
        .number = POGOEggIncubator_FieldNumber_UsesRemaining,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(POGOEggIncubator__storage_, usesRemaining),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "pokemonId",
        .dataTypeSpecific.className = NULL,
        .number = POGOEggIncubator_FieldNumber_PokemonId,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(POGOEggIncubator__storage_, pokemonId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt64,
      },
      {
        .name = "startKmWalked",
        .dataTypeSpecific.className = NULL,
        .number = POGOEggIncubator_FieldNumber_StartKmWalked,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(POGOEggIncubator__storage_, startKmWalked),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "targetKmWalked",
        .dataTypeSpecific.className = NULL,
        .number = POGOEggIncubator_FieldNumber_TargetKmWalked,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(POGOEggIncubator__storage_, targetKmWalked),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[POGOEggIncubator class]
                                     rootClass:[POGOEggIncubatorRoot class]
                                          file:POGOEggIncubatorRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(POGOEggIncubator__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t POGOEggIncubator_ItemId_RawValue(POGOEggIncubator *message) {
  GPBDescriptor *descriptor = [POGOEggIncubator descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGOEggIncubator_FieldNumber_ItemId];
  return GPBGetMessageInt32Field(message, field);
}

void SetPOGOEggIncubator_ItemId_RawValue(POGOEggIncubator *message, int32_t value) {
  GPBDescriptor *descriptor = [POGOEggIncubator descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGOEggIncubator_FieldNumber_ItemId];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

int32_t POGOEggIncubator_IncubatorType_RawValue(POGOEggIncubator *message) {
  GPBDescriptor *descriptor = [POGOEggIncubator descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGOEggIncubator_FieldNumber_IncubatorType];
  return GPBGetMessageInt32Field(message, field);
}

void SetPOGOEggIncubator_IncubatorType_RawValue(POGOEggIncubator *message, int32_t value) {
  GPBDescriptor *descriptor = [POGOEggIncubator descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:POGOEggIncubator_FieldNumber_IncubatorType];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
